"use strict";
let currentOperationId=safeStorage.getItem("fw_v1_current_operation_id")||"";
let currentOperationDraft=null,editingOperationArchiveId="",operationAssignmentGroup="EM 5/42 LF10",operationAssignments={},operationAssignmentRoles={};
const OP_VEHICLES=["EM 5/47 TSF","EM 5/42 LF10"],OP_VEHICLE_CAPACITY=Object.freeze({"EM 5/47 TSF":7,"EM 5/42 LF10":9});
const OP_DEVICES=["Wärmebildkamera","Pressluftatmer","Kettensäge","Sprungpolster","Belüftungsgerät","Stromerzeuger","Tauchpumpe","Wassersauger","Rettungsschere","Rettungsspreizer","Rettungszylinder","Türöffnungswerkzeug"];
const OP_ROLE_ORDER=Object.freeze(["GF","Maschinist","ATF","ATM","WTF","WTM","STF","STM","Melder"]),OP_AGENCIES=["Polizei","Streifendienst","KDD","Kripo","Bundespolizei","Rettungsdienst","RTW","NEF","KTW","RTH","DRK Ortsverein","KBM","Stadt Emmendingen","Stadtwerke","Netze BW","Badenova","THW","DLRG","Abschleppdienst","Straßen-/Autobahnmeisterei","DB-Notfallmanager","Bestatter","Weitere Feuerwehren"];
function operationRoleRank(r){const i=OP_ROLE_ORDER.indexOf(String(r||""));return i<0?99:i}function operationSortNames(n,r){return[...n].sort((a,b)=>operationRoleRank(r?.[a])-operationRoleRank(r?.[b])||operationProtocolName(a).localeCompare(operationProtocolName(b),"de"))}
window.__ffwFinishOperation=async e=>{e?.preventDefault?.();e?.stopPropagation?.();try{if(typeof window.finishOperationZip!=="function")throw Error("Einsatzabschluss-Modul ist nicht geladen");await window.finishOperationZip()}catch(x){console.error(x);showToast?.(`Einsatz konnte nicht abgeschlossen werden: ${x?.message||"unbekannter Fehler"}`,"error")}return false};
function operationSessionKey(){return currentOperationId||""}function startOperationSession(){if(currentOperationId&&entries.some(e=>e.operationId===currentOperationId))return;operationAssignments={};operationAssignmentRoles={};currentOperationId=`op-${today()}-${Date.now()}-${Math.random().toString(16).slice(2)}`;safeStorage.setItem("fw_v1_current_operation_id",currentOperationId);currentOperationDraft=null}function operationEntries(){return entries.filter(e=>e.operationId===currentOperationId)}function operationNames(){return operationEntries().filter(e=>e.status==="Anwesend").map(e=>e.storedName||e.displayName)}function operationProtocolName(v){const n=String(v||"").trim();if(!n.includes(","))return n;const[l,...f]=n.split(",");return[f.join(",").trim(),l.trim()].filter(Boolean).join(" ")}
function operationValue(id){return String(byId(id)?.value||"").trim()}function checkedValues(name){return[...document.querySelectorAll(`#operationReportForm input[name="${name}"]:checked`)].map(x=>x.value)}
function ensureOperationForm(){let s=byId("operationReportForm");if(s)return s;s=document.createElement("section");s.id="operationReportForm";s.className="panel operation-report-form";s.hidden=true;const checks=(a,n)=>a.map(v=>`<label class="operation-check"><input type="checkbox" name="${n}" value="${escapeHtml(v)}"><span>${escapeHtml(v)}</span></label>`).join("");s.innerHTML=`<div class="flow-stage-heading"><span>3</span><div><strong>Einsatzbericht erfassen</strong><small>Mehrere Einsätze am selben Tag werden getrennt gespeichert.</small></div></div><div class="operation-grid"><label>Einsatzdatum<input id="opDate" type="date"></label><label>Einsatznummer<input id="opNumber"></label><label>Einsatzart *<input id="opType"></label><label>Einsatzstelle *<input id="opLocation"></label><label>Einsatzleiter<input id="opLeader"></label><label>ZvD<input id="opZvd"></label></div><fieldset><legend>Zeiten</legend><div class="operation-grid"><label>Alarm *<input id="opAlarm" type="time"></label><label>Ausgerückt<input id="opDeparted" type="time"></label><label>Einsatzstelle<input id="opArrived" type="time"></label><label>Einsatzende<input id="opEnded" type="time"></label><label>Eingerückt<input id="opReturned" type="time"></label></div></fieldset><fieldset><legend>Bericht</legend><label>Lage beim Eintreffen *<textarea id="opSituation"></textarea></label><label>Verlauf der Tätigkeit *<textarea id="opActions"></textarea></label><label>Besondere Vorkommnisse<textarea id="opSpecial"></textarea></label></fieldset><fieldset><legend>Atemschutz</legend><label class="operation-check"><input id="opAtueUsed" type="checkbox"><span>Atemschutzüberwachung wurde durchgeführt</span></label><label class="operation-check"><input id="opAtueDepartment" type="checkbox"><span>Abteilung Emmendingen durchgeführt</span></label><label id="opAtuePersonLabel">ATÜ-Person<select id="opAtuePerson"><option value="">Bitte auswählen</option></select></label><p class="operation-field-hint">Ein Foto des Berichts ist optional.</p></fieldset><div id="operationValidation" hidden></div><div class="operation-actions"><button class="outline-button" id="operationBack" type="button">Zurück</button><button class="primary-button" id="operationFinish" type="button" onclick="return window.__ffwFinishOperation(event)">Einsatz abschließen · Terminpaket</button></div>`;byId("attendanceView").appendChild(s);byId("operationBack").onclick=()=>showOperationForm();const sync=()=>{const used=byId("opAtueUsed")?.checked,department=byId("opAtueDepartment")?.checked,p=byId("opAtuePerson");if(p){p.disabled=department;if(department)p.value=""}byId("opAtuePersonLabel").hidden=department;if(!used||department){resetDocumentReportState();hideDocumentReportUi?.()}else if(String(p?.value||"").trim()&&!documentReportReady)showDocumentReportPanel()};byId("opAtueUsed").onchange=sync;byId("opAtueDepartment").onchange=e=>{if(e.target.checked)byId("opAtueUsed").checked=true;sync()};byId("opAtuePerson").onchange=sync;return s}
function collectOperationData(){return{id:currentOperationId,date:operationValue("opDate")||today(),number:operationValue("opNumber"),type:operationValue("opType"),location:operationValue("opLocation"),leader:operationValue("opLeader"),zvd:operationValue("opZvd"),times:{alarm:operationValue("opAlarm"),departed:operationValue("opDeparted"),arrived:operationValue("opArrived"),ended:operationValue("opEnded"),returned:operationValue("opReturned")},assignments:{...operationAssignments},assignmentRoles:{...operationAssignmentRoles},situation:operationValue("opSituation"),actions:operationValue("opActions"),special:operationValue("opSpecial"),atueUsed:Boolean(byId("opAtueUsed")?.checked),atueDepartment:Boolean(byId("opAtueDepartment")?.checked),atuePerson:operationValue("opAtuePerson"),members:operationNames(),devices:[],deviceAmounts:{},pipes:{},waterSources:[],oil:{},agencies:[],alarmMethods:[]}}
function validateOperation(d){d=d||collectOperationData();const errors=[];if(!d.members?.length)errors.push("Mindestens eine anwesende Einsatzkraft ist erforderlich.");if(!d.type)errors.push("Einsatzart fehlt.");if(!d.location)errors.push("Einsatzstelle fehlt.");if(!d.times?.alarm)errors.push("Alarmzeit fehlt.");if(!d.situation)errors.push("Lage beim Eintreffen fehlt.");if(!d.actions)errors.push("Verlauf der Tätigkeit fehlt.");if(d.atueUsed&&!d.atueDepartment&&!d.atuePerson)errors.push("Bei Atemschutzüberwachung muss eine ATÜ-Person ausgewählt werden.");return{errors,warnings:[]}}
function openOperationReportForm(){const a=byId("operationAssignmentStep");if(a)a.hidden=true;const s=ensureOperationForm();s.hidden=false;const p=byId("opAtuePerson");p.innerHTML='<option value="">Bitte auswählen</option>'+members.filter(m=>!m.ageDepartment&&m.atueQualified).map(m=>`<option>${escapeHtml(nameForTile(m))}</option>`).join("");byId("opDate").value=currentOperationDraft?.date||today();requestAnimationFrame(()=>s.scrollIntoView({behavior:"smooth",block:"start"}))}
function ensureOperationAssignmentStep(){let s=byId("operationAssignmentStep");if(s)return s;s=document.createElement("section");s.id="operationAssignmentStep";s.className="panel operation-assignment-step";s.innerHTML='<div class="flow-stage-heading"><span>3</span><div><strong>Einsatzkräfte zuordnen</strong><small>Alle Teilnehmenden dem LF10, TSF oder der Reserve zuordnen.</small></div></div><div class="operation-assignment-members"></div><div class="operation-assignment-footer"><span></span><button type="button" class="primary-button">Weiter zum Einsatzbericht</button></div>';byId("attendanceView").appendChild(s);s.querySelector(".operation-assignment-members").onclick=e=>{const b=e.target.closest("[data-assignment-name]");if(!b)return;operationAssignments[b.dataset.assignmentName]=b.dataset.assignmentGroup;renderOperationAssignmentStep()};s.querySelector("button").onclick=openOperationReportForm;return s}
function renderOperationAssignmentStep(){const s=ensureOperationAssignmentStep(),names=operationNames(),groups=["EM 5/42 LF10","EM 5/47 TSF","Reserve Einsatzstelle","Reserve Gerätehaus"];s.querySelector(".operation-assignment-members").innerHTML=names.map(n=>`<article><strong>${escapeHtml(operationProtocolName(n))}</strong>${groups.map(g=>`<button type="button" data-assignment-name="${escapeHtml(n)}" data-assignment-group="${g}" class="${operationAssignments[n]===g?"selected":""}">${g}</button>`).join("")}</article>`).join("");const open=names.filter(n=>!operationAssignments[n]).length;s.querySelector(".operation-assignment-footer span").textContent=`${names.length-open} von ${names.length} zugeordnet`;s.querySelector(".operation-assignment-footer button").disabled=!names.length||open>0}
function showOperationForm(){const f=byId("operationReportForm");if(f)f.hidden=true;const s=ensureOperationAssignmentStep();s.hidden=false;renderOperationAssignmentStep()}
function operationPdfEscape(v){return pdfEscape(pdfLatin1(String(v||"")))}function opPdfBytes(v){const t=String(v??""),b=new Uint8Array(t.length);for(let i=0;i<t.length;i++)b[i]=t.charCodeAt(i)&255;return b}function opConcatBytes(p){const l=p.reduce((s,x)=>s+x.length,0),r=new Uint8Array(l);let o=0;for(const x of p){r.set(x,o);o+=x.length}return r}
async function operationPdfBlob(d){d=d||collectOperationData();const rows=(d.members||[]).map(n=>({time:d.times?.alarm||"",name:operationProtocolName(n),status:"Anwesend",role:d.assignmentRoles?.[n]||d.assignments?.[n]||""}));return probePdfBlob(rows,"Einsatz",{present:rows.length,excused:0,missing:0,notApplicable:0},`${d.type||"Einsatz"} · ${d.location||""}`,d.date||today())}
async function showOperationPdfPreview(b,n,f){return Boolean(await f())}function operationCsv(d){d=d||collectOperationData();const h=["Datum","Alarmzeit","Einsatznummer","Einsatzart","Einsatzstelle","Name","Fahrzeug / Reserve","Funktion"],rows=(d.members||[]).map(n=>[d.date,d.times?.alarm,d.number,d.type,d.location,operationProtocolName(n),d.assignments?.[n]||"",d.assignmentRoles?.[n]||""]);return'\ufeff'+[h,...rows].map(r=>r.map(csvCell).join(';')).join('\r\n')}
async function finishOperation(){return window.finishOperationZip?.()}function resetOperationState(){safeStorage.setItem("fw_v1_current_operation_id","");currentOperationId="";currentOperationDraft=null;editingOperationArchiveId="";byId("operationReportForm")?.remove();byId("operationAssignmentStep")?.remove()}
function operationStatisticsData(y){return csvArchive.filter(i=>i.sessionType==="Einsatz"&&String(i.operationData?.date||i.createdAt).startsWith(y))}function renderOperationStatistics(){}function ensureOperationStatisticsPanel(){}function editArchivedOperation(){showToast("Einsatzkorrektur ist in dieser Version nicht verfügbar.","error")}
