let currentOperationId=safeStorage.getItem("fw_v1_current_operation_id")||"";
let currentOperationDraft=null;
let editingOperationArchiveId="";
let operationAssignmentGroup="EM 5/42 LF10";
let operationAssignments={};
let operationAssignmentRoles={};
const OP_VEHICLES=["EM 5/47 TSF","EM 5/42 LF10"];
const OP_VEHICLE_CAPACITY=Object.freeze({"EM 5/47 TSF":7,"EM 5/42 LF10":9});
const OP_DEVICES=["Wärmebildkamera","Pressluftatmer","Kettensäge","Sprungpolster","Belüftungsgerät","Stromerzeuger","Tauchpumpe","Wassersauger","Rettungsschere","Rettungsspreizer","Rettungszylinder","Türöffnungswerkzeug"];
const OP_ROLE_ORDER=Object.freeze(["GF","Maschinist","ATF","ATM","WTF","WTM","STF","STM","Melder"]);
function operationRoleRank(role){const index=OP_ROLE_ORDER.indexOf(String(role||""));return index<0?99:index;}
function operationSortNames(names,roles){return [...names].sort((a,b)=>operationRoleRank(roles?.[a])-operationRoleRank(roles?.[b])||operationProtocolName(a).localeCompare(operationProtocolName(b),"de"));}
const OP_AGENCIES=["Polizei","Streifendienst","KDD","Kripo","Bundespolizei","Rettungsdienst","RTW","NEF","KTW","RTH","DRK Ortsverein","KBM","Stadt Emmendingen","Stadtwerke","Netze BW","Badenova","THW","DLRG","Abschleppdienst","Straßen-/Autobahnmeisterei","DB-Notfallmanager","Bestatter","Weitere Feuerwehren"];
function operationSessionKey(){return currentOperationId||"";}
function startOperationSession(){if(currentOperationId&&entries.some(e=>e.operationId===currentOperationId))return;operationAssignments={};operationAssignmentRoles={};currentOperationId=`op-${today()}-${Date.now()}-${Math.random().toString(16).slice(2)}`;safeStorage.setItem("fw_v1_current_operation_id",currentOperationId);currentOperationDraft=null;}
function operationEntries(){return entries.filter(e=>e.operationId===currentOperationId);}
function operationNames(){return operationEntries().filter(e=>e.status==="Anwesend").map(e=>e.storedName||e.displayName);}
function operationProtocolName(value){const name=String(value||"").trim();if(!name.includes(","))return name;const [last,...firstParts]=name.split(",");const first=firstParts.join(",").trim();return [first,last.trim()].filter(Boolean).join(" ");}
function ensureOperationForm(){
 let section=byId("operationReportForm");if(section)return section;
 section=document.createElement("section");section.id="operationReportForm";section.className="panel operation-report-form";section.hidden=true;
 const checks=(items,name)=>items.map(v=>`<label class="operation-check"><input type="checkbox" name="${name}" value="${escapeHtml(v)}"><span>${escapeHtml(v)}</span></label>`).join("");
 const deviceAmounts=items=>items.map(v=>`<label class="operation-device-amount"><span>${escapeHtml(v)}</span><input type="number" inputmode="numeric" min="0" step="1" value="0" name="deviceAmount" data-device="${escapeHtml(v)}" aria-label="Anzahl ${escapeHtml(v)}"></label>`).join("");
 section.innerHTML=`<div class="flow-stage-heading"><span>3</span><div><strong>Einsatzbericht erfassen</strong><small>Mehrere Einsätze am selben Tag werden getrennt gespeichert.</small></div></div>
 <div class="operation-grid operation-basics"><label>Einsatzdatum<input id="opDate" type="date"></label><label>Einsatznummer<input id="opNumber" placeholder="z. B. 29 / 2026"></label><label>Einsatzart *<input id="opType" placeholder="z. B. B1 Mülleimerbrand"></label><label>Einsatzstelle *<input id="opLocation"></label><label>Einsatzleiter<input id="opLeader"></label><label>ZvD<input id="opZvd"></label><label>Verursacher / Geschädigte<input id="opAffected"></label><label>Anschrift<input id="opAddress"></label></div>
 <fieldset><legend>Alarmierung</legend><div class="operation-check-grid">${checks(["Schleife","telefonisch","per Funk","mündlich","selbst"],"alarmMethod")}</div><label>Schleifennummer<input id="opLoop" value="16134"></label></fieldset>
 <fieldset><legend>Zeiten</legend><div class="operation-grid operation-times"><label>Alarm *<input id="opAlarm" type="time"></label><label>Ausgerückt<input id="opDeparted" type="time"></label><label>Einsatzstelle<input id="opArrived" type="time"></label><label>Einsatzende<input id="opEnded" type="time"></label><label>Eingerückt<input id="opReturned" type="time"></label></div></fieldset>
 <fieldset><legend>Rohre und Wasserentnahme</legend><div class="operation-grid"><label>C-Rohre<input id="opCPipes" min="0" type="number"></label><label>B-Rohre<input id="opBPipes" min="0" type="number"></label><label>Wasserwerfer<input id="opMonitor" min="0" type="number"></label><label>Kleinlöschgeräte<input id="opSmall" min="0" type="number"></label></div><div class="operation-check-grid">${checks(["Tank","Hydrant","Offenes Gewässer","Löschteich"],"waterSource")}</div></fieldset>
 <fieldset><legend>Eingesetzte Geräte</legend><p class="operation-field-hint">Für jedes eingesetzte Gerät die Anzahl eintragen. Nicht eingesetzte Geräte bleiben auf 0.</p><div class="operation-device-grid">${deviceAmounts(OP_DEVICES)}</div><label>Sonstige Geräte<input id="opOtherDevices"></label></fieldset>
 <fieldset><legend>Öleinsatz, optional</legend><div class="operation-grid"><label>Öl-ex hart, Sack<input id="opOilHard" min="0" type="number"></label><label>Oel-ex 82, Sack<input id="opOil82" min="0" type="number"></label><label>Flüssigreiniger, Liter<input id="opCleaner" min="0" step="0.1" type="number"></label><label>Entsorgung, Euro<input id="opDisposal" min="0" step="0.01" type="number"></label></div></fieldset>
 
 <fieldset><legend>Bericht</legend><label>Lage und Zustand beim Eintreffen *<textarea id="opSituation" rows="4"></textarea></label><label>Verlauf der Tätigkeit *<textarea id="opActions" rows="5"></textarea></label><label>Menschenrettung, Unglücksfälle oder Verletzungen<textarea id="opPersons" rows="3"></textarea></label><label>Besondere Vorkommnisse<textarea id="opSpecial" rows="3"></textarea></label></fieldset>
 <fieldset><legend>Weitere Kräfte und Behörden</legend><div class="operation-check-grid">${checks(OP_AGENCIES,"agency")}</div><label>Sonstige beteiligte Stellen<input id="opOtherAgencies"></label></fieldset>
 <fieldset><legend>Atemschutz</legend><label class="operation-check"><input id="opAtueUsed" type="checkbox"><span>Atemschutzüberwachung wurde durchgeführt</span></label><label class="operation-check"><input id="opAtueDepartment" type="checkbox"><span>Abteilung Emmendingen durchgeführt</span></label><label id="opAtuePersonLabel">ATÜ-Person<select id="opAtuePerson"><option value="">Bitte auswählen</option></select></label><p class="operation-field-hint">Bei „Abteilung Emmendingen durchgeführt“ ist keine ATÜ-Person und kein eingescanntes Dokument erforderlich.</p></fieldset>
 <div id="operationValidation" class="operation-validation" hidden></div><div class="operation-actions"><button class="outline-button" id="operationBack" type="button">Zurück zur Zuordnung</button><button class="primary-button" id="operationFinish" type="button">Einsatz abschließen · CSV + PDF</button></div>`;
 byId("attendanceView").appendChild(section);
 byId("operationBack").onclick=()=>{ensureOperationForm().hidden=true;showOperationForm();};
 byId("operationFinish").onclick=async event=>{
   event.preventDefault();
   const button=event.currentTarget;
   const originalText=button.textContent;
   if(typeof window.finishOperationZip!=="function")return showToast("Einsatzabschluss ist nicht geladen. Bitte Seite vollständig neu laden.","error");
   button.textContent="Einsatz wird vorbereitet …";
   button.setAttribute("aria-busy","true");
   try{await window.finishOperationZip();}
   catch(error){console.error("Einsatzabschluss fehlgeschlagen",error);showToast(`Einsatz konnte nicht abgeschlossen werden: ${error?.message||"unbekannter Fehler"}`,"error");}
   finally{button.textContent=originalText;button.removeAttribute("aria-busy");button.disabled=false;}
 };
 const syncAtueMode=()=>{
   const used=Boolean(byId("opAtueUsed")?.checked),department=Boolean(byId("opAtueDepartment")?.checked);
   const person=byId("opAtuePerson"),label=byId("opAtuePersonLabel");
   if(person){person.disabled=department;if(department)person.value="";}
   if(label)label.hidden=department;
   if(!used||department){resetDocumentReportState();hideDocumentReportUi?.();return;}
   if(String(person?.value||"").trim()&&!documentReportReady)showDocumentReportPanel();
 };
 byId("opAtueUsed").addEventListener("change",syncAtueMode);
 byId("opAtueDepartment").addEventListener("change",event=>{if(event.target.checked)byId("opAtueUsed").checked=true;syncAtueMode();});
 byId("opAtuePerson").addEventListener("change",syncAtueMode);
 return section;
}
function operationValue(id){return String(byId(id)?.value||"").trim();}
function checkedValues(name){return [...document.querySelectorAll(`#operationReportForm input[name="${name}"]:checked`)].map(x=>x.value);}
function collectOperationData(){const deviceAmounts=Object.fromEntries([...document.querySelectorAll('#operationReportForm input[name="deviceAmount"]')].map(input=>[input.dataset.device,Math.max(0,Number.parseInt(input.value,10)||0)]));const devices=OP_DEVICES.filter(device=>deviceAmounts[device]>0);return {id:currentOperationId,date:operationValue("opDate")||today(),number:operationValue("opNumber"),type:operationValue("opType"),location:operationValue("opLocation"),leader:operationValue("opLeader"),zvd:operationValue("opZvd"),affected:operationValue("opAffected"),address:operationValue("opAddress"),alarmMethods:checkedValues("alarmMethod"),loop:operationValue("opLoop")||"16134",times:{alarm:operationValue("opAlarm"),departed:operationValue("opDeparted"),arrived:operationValue("opArrived"),ended:operationValue("opEnded"),returned:operationValue("opReturned")},pipes:{c:operationValue("opCPipes"),b:operationValue("opBPipes"),monitor:operationValue("opMonitor"),small:operationValue("opSmall")},waterSources:checkedValues("waterSource"),devices,deviceAmounts,otherDevices:operationValue("opOtherDevices"),oil:{hard:operationValue("opOilHard"),oil82:operationValue("opOil82"),cleaner:operationValue("opCleaner"),disposal:operationValue("opDisposal")},assignments:{...operationAssignments},assignmentRoles:{...operationAssignmentRoles},vehicles:OP_VEHICLES.filter(vehicle=>Object.values(operationAssignments).includes(vehicle)),otherVehicles:operationValue("opOtherVehicles"),situation:operationValue("opSituation"),actions:operationValue("opActions"),persons:operationValue("opPersons"),special:operationValue("opSpecial"),agencies:checkedValues("agency"),otherAgencies:operationValue("opOtherAgencies"),atueUsed:Boolean(byId("opAtueUsed")?.checked),atueDepartment:Boolean(byId("opAtueDepartment")?.checked),atuePerson:operationValue("opAtuePerson"),members:operationNames()};}
function timeMinutes(value){if(!/^\d{2}:\d{2}$/.test(value))return null;const [h,m]=value.split(":").map(Number);return h*60+m;}
function validateOperation(d){const errors=[],warnings=[];if(!d.members.length)errors.push("Mindestens eine anwesende Einsatzkraft ist erforderlich.");if(!d.type)errors.push("Einsatzart fehlt.");if(!d.location)errors.push("Einsatzstelle fehlt.");if(!d.times.alarm)errors.push("Alarmzeit fehlt.");if(!d.situation)errors.push("Lage beim Eintreffen fehlt.");if(!d.actions)errors.push("Verlauf der Tätigkeit fehlt.");const seq=[d.times.alarm,d.times.departed,d.times.arrived,d.times.ended,d.times.returned].filter(Boolean).map(timeMinutes);for(let i=1;i<seq.length;i++)if(seq[i]<seq[i-1]){warnings.push("Die Zeitreihenfolge ist ungewöhnlich. Bitte prüfen.");break;}if(d.devices.includes("Pressluftatmer")&&!d.atueUsed)warnings.push("Pressluftatmer ist ausgewählt, aber keine Atemschutzüberwachung angegeben.");if(d.atueUsed&&!d.atueDepartment&&!d.atuePerson)errors.push("Bei Atemschutzüberwachung muss eine ATÜ-Person ausgewählt oder „Abteilung Emmendingen durchgeführt“ aktiviert werden.");const duplicate=csvArchive.some(item=>item.id!==editingOperationArchiveId&&item.sessionType==="Einsatz"&&item.operationData?.number&&d.number&&item.operationData.number===d.number);if(duplicate)errors.push("Diese Einsatznummer ist bereits vorhanden.");return {errors,warnings};}
function setOperationChecks(name,values){const selected=new Set(values||[]);document.querySelectorAll(`#operationReportForm input[name="${name}"]`).forEach(input=>{input.checked=selected.has(input.value);});}
function fillOperationForm(d){if(!d)return;const values={opDate:d.date,opNumber:d.number,opType:d.type,opLocation:d.location,opLeader:d.leader,opZvd:d.zvd,opAffected:d.affected,opAddress:d.address,opLoop:d.loop,opAlarm:d.times?.alarm,opDeparted:d.times?.departed,opArrived:d.times?.arrived,opEnded:d.times?.ended,opReturned:d.times?.returned,opCPipes:d.pipes?.c,opBPipes:d.pipes?.b,opMonitor:d.pipes?.monitor,opSmall:d.pipes?.small,opOtherDevices:d.otherDevices,opOilHard:d.oil?.hard,opOil82:d.oil?.oil82,opCleaner:d.oil?.cleaner,opDisposal:d.oil?.disposal,opOtherVehicles:d.otherVehicles,opSituation:d.situation,opActions:d.actions,opPersons:d.persons,opSpecial:d.special,opOtherAgencies:d.otherAgencies,opAtuePerson:d.atuePerson};Object.entries(values).forEach(([id,value])=>{const el=byId(id);if(el)el.value=value??"";});setOperationChecks("alarmMethod",d.alarmMethods);setOperationChecks("waterSource",d.waterSources);const legacyDevices=new Set(Array.isArray(d.devices)?d.devices:[]);document.querySelectorAll('#operationReportForm input[name="deviceAmount"]').forEach(input=>{const stored=d.deviceAmounts?.[input.dataset.device];input.value=stored??(legacyDevices.has(input.dataset.device)?1:0);});setOperationChecks("vehicle",d.vehicles);setOperationChecks("agency",d.agencies);byId("opAtueUsed").checked=Boolean(d.atueUsed);byId("opAtueDepartment").checked=Boolean(d.atueDepartment);byId("opAtuePerson").disabled=Boolean(d.atueDepartment);byId("opAtuePersonLabel").hidden=Boolean(d.atueDepartment);byId("operationFinish").textContent=editingOperationArchiveId?"ZIP-Terminpaket überschreiben":"Einsatz abschließen · Terminpaket";}
function openOperationReportForm(){syncHomeFlowProgress?.(4);const assignment=byId("operationAssignmentStep");if(assignment)assignment.hidden=true;const section=ensureOperationForm();section.hidden=false;const select=byId("opAtuePerson");select.innerHTML='<option value="">Bitte auswählen</option>'+members.filter(m=>!m.ageDepartment&&m.atueQualified).map(m=>`<option>${escapeHtml(nameForTile(m))}</option>`).join("");if(currentOperationDraft)fillOperationForm(currentOperationDraft);else{byId("opDate").value=today();byId("opLoop").value="16134";}requestAnimationFrame(()=>section.scrollIntoView({behavior:"smooth",block:"start"}));}
function operationMemberByName(name){return members.find(member=>nameForStorage(member)===name||nameForTile(member)===name)||null;}
function operationRoleAllowed(name,role,group){
 const member=operationMemberByName(name);
 if(!member)return role!=="Maschinist"&&role!=="GF";
 if(role==="GF")return Array.isArray(member.roles)&&member.roles.includes("GF");
 if(role==="Maschinist"){
  const vehicle=group.includes("LF10")?"LF":"TSF";
  const allowed=Array.isArray(member.machinistVehicles)?member.machinistVehicles:[];
  const vehicleAllowed=vehicle==="LF"?allowed.includes("LF"):allowed.includes("TSF")||allowed.includes("LF");
  const licenseState=typeof driverLicenseState==="function"?driverLicenseState(member):"valid";
  return vehicleAllowed&&(licenseState==="valid"||licenseState==="soon");
 }
 return true;
}
function ensureOperationAssignmentStep(){let section=byId("operationAssignmentStep");if(section)return section;section=document.createElement("section");section.id="operationAssignmentStep";section.className="panel operation-assignment-step";section.innerHTML=`<div class="flow-stage-heading"><span>3</span><div><strong>Einsatzkräfte zuordnen</strong><small>Alle Teilnehmenden einem Fahrzeug oder einer Reserve zuordnen.</small></div></div><div class="operation-assignment-tabs" role="tablist"></div><div class="operation-assignment-summary"></div><div class="operation-assignment-members"></div><div class="operation-assignment-footer"><span></span><button type="button" class="primary-button" disabled>Weiter zum Einsatzbericht</button></div>`;const host=byId("attendanceView");
 if(!host)throw new Error("Einsatz-Zuordnung konnte nicht eingebunden werden.");
 host.appendChild(section);section.querySelector(".operation-assignment-tabs").addEventListener("click",event=>{const button=event.target.closest("[data-assignment-group]");if(!button)return;operationAssignmentGroup=button.dataset.assignmentGroup;renderOperationAssignmentStep();});section.querySelector(".operation-assignment-members").addEventListener("click",event=>{const button=event.target.closest("[data-assignment-name]");if(!button)return;const name=button.dataset.assignmentName,current=operationAssignments[name]||"",capacity=OP_VEHICLE_CAPACITY[operationAssignmentGroup];if(capacity&&current!==operationAssignmentGroup&&Object.values(operationAssignments).filter(group=>group===operationAssignmentGroup).length>=capacity)return showToast(`${operationAssignmentGroup} ist voll. Es stehen ${capacity} Plätze zur Verfügung.`,"error");operationAssignments[name]=operationAssignmentGroup;renderOperationAssignmentStep();});section.querySelector(".operation-assignment-summary").addEventListener("click",event=>{const button=event.target.closest("[data-remove-assignment]");if(!button)return;delete operationAssignments[button.dataset.removeAssignment];renderOperationAssignmentStep();});section.querySelector(".operation-assignment-summary").addEventListener("change",event=>{const select=event.target.closest("[data-assignment-role]");if(!select)return;operationAssignmentRoles[select.dataset.assignmentRole]=select.value;renderOperationAssignmentStep();});section.querySelector(".operation-assignment-footer button").onclick=()=>{const names=operationNames();if(names.some(name=>!operationAssignments[name]))return showToast("Bitte alle Einsatzkräfte zuordnen.","error");if(names.some(name=>OP_VEHICLES.includes(operationAssignments[name])&&!operationAssignmentRoles[name]))return showToast("Bitte allen Fahrzeugbesatzungen eine Funktion zuordnen.","error");openOperationReportForm();};return section;}
function renderOperationAssignmentStep(){
 const section=ensureOperationAssignmentStep(),groups=["EM 5/42 LF10","EM 5/47 TSF","Reserve Einsatzstelle","Reserve Gerätehaus"],names=operationNames();
 Object.keys(operationAssignments).forEach(name=>{if(!names.includes(name)){delete operationAssignments[name];delete operationAssignmentRoles[name];}});
 const tabs=section.querySelector(".operation-assignment-tabs");
 tabs.innerHTML=groups.map(group=>`<button type="button" role="tab" class="${group===operationAssignmentGroup?"selected":""}" data-assignment-group="${escapeHtml(group)}"><strong>${escapeHtml(group)}</strong><span>${names.filter(name=>operationAssignments[name]===group).length}${OP_VEHICLE_CAPACITY[group]?` / ${OP_VEHICLE_CAPACITY[group]}`:""}</span></button>`).join("");
 section.querySelector(".operation-assignment-members").innerHTML=names.map(name=>{const assigned=operationAssignments[name]||"";return `<button type="button" class="operation-assignment-person${assigned?" assigned":""}" data-assignment-name="${escapeHtml(name)}"><strong>${escapeHtml(operationProtocolName(name))}</strong><small>${assigned?escapeHtml(assigned):`Zu ${escapeHtml(operationAssignmentGroup)} hinzufügen`}</small></button>`;}).join("")||'<p class="empty-state">Keine anwesenden Einsatzkräfte erfasst.</p>';
 const vehicleCard=(group,image,roles)=>{const assigned=operationSortNames(names.filter(name=>operationAssignments[name]===group),operationAssignmentRoles);const used=new Set(assigned.map(name=>operationAssignmentRoles[name]).filter(Boolean));return `<article class="operation-vehicle-crew"><header><img src="${image}" alt="${escapeHtml(group)}"><div><strong>${escapeHtml(group)}</strong><small>Funktion je Person auswählen</small></div></header><div>${assigned.map(name=>{let current=operationAssignmentRoles[name]||"";if(current&&!operationRoleAllowed(name,current,group)){delete operationAssignmentRoles[name];current="";}const availableRoles=roles.filter(role=>operationRoleAllowed(name,role,group));return `<label><span>${escapeHtml(operationProtocolName(name))}</span><select data-assignment-role="${escapeHtml(name)}"><option value="">Funktion auswählen</option>${availableRoles.map(role=>`<option value="${escapeHtml(role)}"${current===role?" selected":""}${used.has(role)&&current!==role?" disabled":""}>${escapeHtml(role)}</option>`).join("")}</select><button type="button" data-remove-assignment="${escapeHtml(name)}" aria-label="Zuordnung entfernen">×</button></label>`;}).join("")||"<p>Noch niemand zugeordnet</p>"}</div></article>`;};
 const reserveCard=group=>{const assigned=names.filter(name=>operationAssignments[name]===group);return `<article class="operation-reserve-crew"><strong>${escapeHtml(group)}</strong><div>${assigned.map(name=>`<button type="button" data-remove-assignment="${escapeHtml(name)}">${escapeHtml(operationProtocolName(name))} ×</button>`).join("")||"<span>Noch niemand zugeordnet</span>"}</div></article>`;};
 section.querySelector(".operation-assignment-summary").innerHTML=`<div class="operation-vehicle-layout">${vehicleCard("EM 5/42 LF10","taktik-lf10.png",GROUP_ROLES)}${vehicleCard("EM 5/47 TSF","taktik-tsf.png",STAFF_ROLES)}</div><div class="operation-reserve-layout">${reserveCard("Reserve Einsatzstelle")}${reserveCard("Reserve Gerätehaus")}</div>`;
 const open=names.filter(name=>!operationAssignments[name]).length,openRoles=names.filter(name=>OP_VEHICLES.includes(operationAssignments[name])&&!operationAssignmentRoles[name]).length;
 section.querySelector(".operation-assignment-footer span").textContent=`${names.length-open} von ${names.length} zugeordnet · ${open} offen${openRoles?` · ${openRoles} Funktion(en) offen`:""}`;
 section.querySelector(".operation-assignment-footer button").disabled=!names.length||open>0||openRoles>0;
}
function showOperationForm(){syncHomeFlowProgress?.(3);if(currentOperationDraft?.assignments)operationAssignments={...currentOperationDraft.assignments};if(currentOperationDraft?.assignmentRoles)operationAssignmentRoles={...currentOperationDraft.assignmentRoles};const form=byId("operationReportForm");if(form)form.hidden=true;const section=ensureOperationAssignmentStep();section.hidden=false;renderOperationAssignmentStep();requestAnimationFrame(()=>section.scrollIntoView({behavior:"smooth",block:"start"}));}
function editArchivedOperation(id){const item=csvArchive.find(entry=>entry.id===id&&entry.sessionType==="Einsatz");if(!item?.operationData)return showToast("Für diesen Einsatz sind keine strukturierten Korrekturdaten vorhanden.","error");editingOperationArchiveId=id;sessionType="Einsatz";currentOperationId=`edit-${id}`;safeStorage.setItem("fw_v1_current_operation_id",currentOperationId);operationAssignments={...(item.operationData.assignments||{})};operationAssignmentRoles={...(item.operationData.assignmentRoles||{})};currentOperationDraft=typeof structuredClone==="function"?structuredClone(item.operationData):JSON.parse(JSON.stringify(item.operationData));entries=entries.filter(entry=>entry.operationId!==currentOperationId);const names=new Set(currentOperationDraft.members||[]);members.filter(member=>names.has(nameForStorage(member))||names.has(nameForTile(member))).forEach(member=>entries.unshift({id:makeId(),date:currentOperationDraft.date||today(),time:currentOperationDraft.times?.alarm||"",displayName:nameForTile(member),storedName:nameForStorage(member),role:"",status:"Anwesend",sessionType:"Einsatz",operationId:currentOperationId}));saveEntries();chosenRole="Anwesend";chosenMemberIds.clear();renderSessionType();renderMembers();renderRoles();renderEntries();showView("attendanceView");setHomeFlowStage(3);showOperationForm();showToast("Einsatzkorrektur geöffnet. Nach Änderungen PDF prüfen und final hochladen.");}
function operationPdfEscape(v){return pdfEscape(pdfLatin1(String(v||"")));}
function operationWrap(text,max=92){const words=String(text||"").split(/\s+/),out=[];let line="";for(const w of words){if((line+" "+w).trim().length>max){out.push(line);line=w}else line=(line+" "+w).trim()}if(line)out.push(line);return out;}
function opPdfBytes(value){const text=String(value??"");const bytes=new Uint8Array(text.length);for(let i=0;i<text.length;i++)bytes[i]=text.charCodeAt(i)&255;return bytes;}
function opConcatBytes(parts){const length=parts.reduce((sum,part)=>sum+part.length,0),result=new Uint8Array(length);let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length;}return result;}
function opPdfText(ops,x,y,size,value,bold=false){ops.push(`BT /${bold?"F2":"F1"} ${size} Tf ${x} ${y} Td (${operationPdfEscape(value)}) Tj ET`);}
function opLine(ops,x1,y1,x2,y2,width=.7){ops.push(`${width} w ${x1} ${y1} m ${x2} ${y2} l S`);}
function opRect(ops,x,y,w,h,fill=false){ops.push(`${x} ${y} ${w} ${h} re ${fill?"B":"S"}`);}
function opWrap(text,max=85){return operationWrap(String(text||"-"),max);}
function opParagraph(ops,x,y,text,max=85,limit=8,size=8.3,leading=12){opWrap(text,max).slice(0,limit).forEach((line,i)=>opPdfText(ops,x,y-i*leading,size,line));}
function opField(ops,label,value,x,y,labelWidth=105,totalWidth=470){opPdfText(ops,x,y,9,label,true);opPdfText(ops,x+labelWidth,y,9,value||"-");opLine(ops,x+labelWidth-4,y-3,x+totalWidth,y-3,.45);}
function opSection(ops,title,y){ops.push(`0.88 0.88 0.88 rg 40 ${y-3} 515 19 re f 0 0 0 rg`);opRect(ops,40,y-3,515,19);opPdfText(ops,47,y+3,9,title,true);return y-24;}
function opCheckbox(ops,x,y,label,checked){opRect(ops,x,y-2,10,10);if(checked){opLine(ops,x+2,y+3,x+5,y,1.2);opLine(ops,x+5,y,x+9,y+7,1.2);}opPdfText(ops,x+15,y,8.2,label);}
function opTableRow(ops,y,cells,widths,height=18,bold=false){let x=40;cells.forEach((cell,i)=>{opRect(ops,x,y-height,widths[i],height);opPdfText(ops,x+4,y-height+6,8,String(cell||""),bold);x+=widths[i];});return y-height;}
function opPageHeader(ops,page){ops.push('0.90 0.90 0.90 rg 70 798 455 24 re f 0 0 0 rg');opPdfText(ops,167,806,14,'EINSATZBERICHT Feuerwehr Emmendingen',true);opPdfText(ops,40,777,9,'Feuerwehr Emmendingen, Abt. Wasser');opPdfText(ops,480,777,8,`Seite ${page} / 2`);}
async function operationPdfBlob(d){
 const objects=[null],add=value=>(objects.push(value),objects.length-1),font=add(opPdfBytes('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>')),bold=add(opPdfBytes('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>')),pagesId=add(null),pageIds=[];
 const streams=[];
 {
  const ops=['0 0 0 RG 0 0 0 rg'];opPageHeader(ops,1);let y=750;
  opField(ops,'Einsatz Nr.',d.number||'XX / 2026',45,y);y-=23;opField(ops,'Einsatzart',d.type,45,y);y-=23;opField(ops,'Einsatzstelle',d.location,45,y);y-=23;opField(ops,'Einsatzleiter',d.leader,45,y);y-=23;opField(ops,'ZvD',d.zvd,45,y);y-=23;opField(ops,'Verursacher / Geschädigte',d.affected,45,y,138);y-=23;opField(ops,'Anschrift',d.address,45,y);y-=29;
  y=opSection(ops,'Alarmierung',y+8);const methods=['Schleife','telefonisch','per Funk','mündlich','selbst'];methods.forEach((m,i)=>opCheckbox(ops,48+i*99,y,m,d.alarmMethods.includes(m)));y-=22;opField(ops,'Schleifennummer',d.loop,45,y);y-=28;
  y=opSection(ops,'Uhrzeiten',y+8);y=opTableRow(ops,y,['Alarm','Ausgerückt','Einsatzstelle','Einsatzende','Eingerückt'],[103,103,103,103,103],20,true);y=opTableRow(ops,y,[d.times.alarm,d.times.departed,d.times.arrived,d.times.ended,d.times.returned],[103,103,103,103,103],22);y-=20;opPdfText(ops,45,y,8,`Datum: ${formatDisplayDate(d.date)}`);y-=24;
  y=opSection(ops,'Lage und Zustand beim Eintreffen',y);opParagraph(ops,48,y,d.situation,91,5);y-=68;
  y=opSection(ops,'Löschmittel und Wasserentnahme',y+8);opPdfText(ops,48,y,8.4,`C-Rohre: ${d.pipes.c||0}     B-Rohre: ${d.pipes.b||0}     Wasserwerfer: ${d.pipes.monitor||0}     Kleinlöschgeräte: ${d.pipes.small||0}`);y-=20;['Tank','Hydrant','Offenes Gewässer','Löschteich'].forEach((w,i)=>opCheckbox(ops,48+i*126,y,w,d.waterSources.includes(w)));y-=28;
  y=opSection(ops,'Eingesetzte Geräte',y+8);const dev=OP_DEVICES;for(let row=0;row<3;row++){for(let col=0;col<4;col++){const item=dev[row*4+col];const amount=Number(d.deviceAmounts?.[item]??(d.devices.includes(item)?1:0));opCheckbox(ops,48+col*126,y-row*18,`${item}${amount>0?` (${amount})`:""}`,amount>0);}}y-=62;opField(ops,'Sonstige Geräte',d.otherDevices,45,y);y-=28;
  y=opSection(ops,'Angaben bei Öleinsätzen',y+8);y=opTableRow(ops,y,['Öl-ex hart','Oel-ex 82','Flüssigreiniger','Entsorgung'],[129,129,129,128],18,true);y=opTableRow(ops,y,[`${d.oil.hard||0} Sack`,`${d.oil.oil82||0} Sack`,`${d.oil.cleaner||0} Liter`,`${d.oil.disposal||0} Euro`],[129,129,129,128],20);
  streams.push(ops.join('\n'));
 }
 {
  const ops=['0 0 0 RG 0 0 0 rg'];opPageHeader(ops,2);let y=750;
  y=opSection(ops,'Verlauf der Tätigkeit (Brandbekämpfung / Löscherfolg / Technische Rettung / Hilfeleistung)',y+8);opParagraph(ops,48,y,d.actions,91,10);y-=132;
  y=opSection(ops,'Fahrzeug- und Reservezuordnung',y+8);
  const assignmentGroups=['EM 5/42 LF10','EM 5/47 TSF','Reserve Einsatzstelle','Reserve Gerätehaus'];
  const assignmentLines=Object.fromEntries(assignmentGroups.map(group=>[group,operationSortNames(d.members.filter(name=>d.assignments?.[name]===group),d.assignmentRoles).map(name=>`${operationProtocolName(name)}${d.assignmentRoles?.[name]?` (${d.assignmentRoles[name]})`:''}`)]));
  const assignmentBox=(group,x,top,width,height)=>{opRect(ops,x,top-height,width,height);opPdfText(ops,x+5,top-13,8,group,true);const names=assignmentLines[group].length?assignmentLines[group]:['-'];const available=height-22,leading=Math.max(7,Math.min(9,available/Math.max(1,names.length))),fontSize=leading<8?5.8:7.0;names.forEach((name,index)=>{const maxChars=fontSize<6?62:50,value=name.length>maxChars?`${name.slice(0,maxChars-1)}…`:name;opPdfText(ops,x+7,top-24-index*leading,fontSize,value);});};
  const assignmentRows=[['EM 5/42 LF10','EM 5/47 TSF'],['Reserve Einsatzstelle','Reserve Gerätehaus']];
  for(const pair of assignmentRows){const lineCount=Math.max(1,assignmentLines[pair[0]].length,assignmentLines[pair[1]].length),height=Math.max(42,24+lineCount*9);assignmentBox(pair[0],40,y,255,height);assignmentBox(pair[1],295,y,260,height);y-=height+10;}
  y-=8;
  y=opSection(ops,'Personalangaben bei Menschenrettung, Unglücksfällen oder Verletzungen',y);opParagraph(ops,48,y-4,d.persons,91,4);y-=68;
  y=opSection(ops,'Besondere Vorkommnisse',y+8);opParagraph(ops,48,y,d.special,91,4);y-=62;
  y=opSection(ops,'Weitere Kräfte und Behörden',y+8);const agencies=[...d.agencies,d.otherAgencies].filter(Boolean);opParagraph(ops,48,y,agencies.join(', '),91,5);y-=75;
  y=opSection(ops,'Einsatzleitung und Atemschutz',y+8);opField(ops,'Einsatzleiter',d.leader,45,y);y-=21;opField(ops,'ZvD',d.zvd,45,y);y-=21;opField(ops,'Atemschutzüberwachung',d.atueUsed?(d.atueDepartment?'Ja, durch Abt. Emmendingen':`Ja, ${d.atuePerson}`):'Nein',45,y,138);y-=38;
  opPdfText(ops,45,y,8.5,`Emmendingen, ${formatDisplayDate(d.date)}`,true);
  streams.push(ops.join('\n'));
 }
 for(const stream of streams){const bytes=opPdfBytes(stream),cid=add(opPdfBytes(`<< /Length ${bytes.length} >>\nstream\n${stream}\nendstream`));pageIds.push(add(opPdfBytes(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${cid} 0 R >>`)));}
 objects[pagesId]=opPdfBytes(`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] >>`);const catalog=add(opPdfBytes(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`)),parts=[opPdfBytes('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')],offsets=[0];let length=parts[0].length;for(let i=1;i<objects.length;i++){offsets[i]=length;const part=opConcatBytes([opPdfBytes(`${i} 0 obj\n`),objects[i],opPdfBytes('\nendobj\n')]);parts.push(part);length+=part.length;}const xref=length;let tail=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)tail+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';tail+=`trailer\n<< /Size ${objects.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(opPdfBytes(tail));return new Blob(parts,{type:'application/pdf'});
}
async function showOperationPdfPreview(blob,fileName,onFinalUpload){
  // Keine zusätzliche Vorschau oder zweite Bestätigung mehr.
  document.querySelectorAll("#operationPdfPreviewDialog,.operation-pdf-preview-dialog").forEach(node=>{try{node.close?.();}catch(error){}node.remove();});
  return Boolean(await onFinalUpload());
}
function operationCsv(d){
 const join=value=>(Array.isArray(value)?value:[]).filter(Boolean).join(", ");
 const yes=value=>value?"Ja":"Nein";
 const assignments=group=>d.members.filter(name=>d.assignments?.[name]===group).map(name=>`${operationProtocolName(name)}${d.assignmentRoles?.[name]?` (${d.assignmentRoles[name]})`:""}`).join(", ");
 const devices=OP_DEVICES.map(device=>{const amount=Number(d.deviceAmounts?.[device]??(d.devices.includes(device)?1:0));return amount>0?`${device}: ${amount}`:"";}).filter(Boolean).join(", ");
 const values={
  "Datum":formatDisplayDate(d.date),"Alarmzeit":d.times.alarm,"Ausgerückt":d.times.departed,"Einsatzstelle Zeit":d.times.arrived,"Einsatzende":d.times.ended,"Eingerückt":d.times.returned,
  "Einsatznummer":d.number,"Einsatzart":d.type,"Einsatzstelle":d.location,"Einsatzleiter":d.leader,"ZvD":d.zvd,"Verursacher / Geschädigte":d.affected,"Anschrift":d.address,
  "Alarmierung":join(d.alarmMethods),"Schleifennummer":d.loop,"C-Rohre":d.cPipes,"B-Rohre":d.bPipes,"Wasserwerfer":d.monitor,"Kleinlöschgeräte":d.small,"Wasserentnahme":join(d.waterSources),
  "Eingesetzte Geräte":devices,"Sonstige Geräte":d.otherDevices,"Öl-ex hart, Sack":d.oil?.hard,"Öl-ex 82, Sack":d.oil?.oil82,"Reinigungsmittel, Kanister":d.oil?.cleaner,"Entsorgung":d.oil?.disposal,
  "Lage beim Eintreffen":d.situation,"Verlauf der Tätigkeit":d.actions,"Personalangaben":d.persons,"Besondere Vorkommnisse":d.special,"Weitere Kräfte und Behörden":join(d.agencies),"Sonstige beteiligte Stellen":d.otherAgencies,
  "Atemschutzüberwachung":yes(d.atueUsed),"ATÜ durch Abteilung Emmendingen":yes(d.atueDepartment),"ATÜ-Person":d.atuePerson,
  "EM 5/42 LF10":assignments("EM 5/42 LF10"),"EM 5/47 TSF":assignments("EM 5/47 TSF"),"Reserve Einsatzstelle":assignments("Reserve Einsatzstelle"),"Reserve Gerätehaus":assignments("Reserve Gerätehaus")
 };
 const header=[...Object.keys(values),"Name","Status","Fahrzeug / Reserve","Funktion"];
 const rows=operationSortNames(d.members,d.assignmentRoles).map(name=>[...Object.values(values),operationProtocolName(name),"Anwesend",d.assignments?.[name]||"",d.assignmentRoles?.[name]||""]);
 return '\ufeff'+[header,...rows].map(row=>row.map(value=>csvCell(value??"")).join(';')).join('\r\n');
}
async function finishOperation(){
  // Sicherheitsdelegation: Der Einsatzabschluss darf niemals CSV und PDF
  // einzeln ausgeben. Die einzige Implementierung liegt im ZIP-Modul.
  if(typeof window.finishOperationZip!=="function"){
    showToast("ZIP-Terminpaket-Funktion ist noch nicht geladen.","error");
    return false;
  }
  return window.finishOperationZip();
}

function resetOperationState(){safeStorage.setItem("fw_v1_current_operation_id","");currentOperationId="";currentOperationDraft=null;editingOperationArchiveId="";const s=byId("operationReportForm");if(s){s.remove();}chosenMemberIds.clear();chosenMemberId="";chosenRole="";currentProbeDate=systemToday();}
function operationStatisticsData(year){return csvArchive.filter(i=>i.sessionType==="Einsatz"&&String(i.operationData?.date||i.createdAt).startsWith(year));}
function renderOperationStatistics(){const year=selectedStatisticsYear||String(new Date().getFullYear()),items=operationStatisticsData(year),box=byId("operationStatisticsPanel");if(!box)return;const types=new Map(),membersMap=new Map();items.forEach(i=>{const d=i.operationData||{};types.set(d.type||"Unbekannt",(types.get(d.type||"Unbekannt")||0)+1);(d.members||[]).forEach(n=>membersMap.set(n,(membersMap.get(n)||0)+1));});box.querySelector("[data-op-count]").textContent=items.length;box.querySelector("[data-op-atue]").textContent=items.filter(i=>i.operationData?.atueUsed).length;box.querySelector("[data-op-types]").innerHTML=[...types.entries()].sort((a,b)=>b[1]-a[1]).map(([n,c])=>renderMetric("",n,c,"red")).join("");box.querySelector("[data-op-members]").innerHTML=[...membersMap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([n,c])=>renderMetric("",n,c,"blue")).join("");}
function ensureOperationStatisticsPanel(){if(byId("operationStatisticsPanel"))return;const anchor=byId("settingsStatisticsView")?.querySelector(".statistics-grid");if(!anchor)return;const panel=document.createElement("article");panel.id="operationStatisticsPanel";panel.className="panel statistics-panel operation-statistics-panel";panel.innerHTML=`<div class="panel-heading"><span class="step yellow">EINSATZ</span><h3>Einsatzstatistik</h3></div><div class="statistics-kpis"><div><span>Einsätze</span><strong data-op-count>0</strong></div><div><span>mit ATÜ</span><strong data-op-atue>0</strong></div></div><h4>Einsatzarten</h4><div class="metric-list" data-op-types></div><h4>Teilnahmen je Mitglied, Top 10</h4><div class="metric-list" data-op-members></div>`;anchor.insertAdjacentElement("afterend",panel);}
