"use strict";
const OD_CLIENT_KEY="fw_onedrive_client_id",OD_TOKEN_KEY="fw_onedrive_tokens",OD_PKCE_KEY="fw_onedrive_pkce",OD_STATE_FILE="feuerwehr-wasser-daten.json";
let oneDriveBusy=false,oneDriveTimer=null,oneDriveApplying=false;
const odRedirect=()=>location.origin+location.pathname;
const odConfig=()=>({clientId:localStorage.getItem(OD_CLIENT_KEY)||"",authority:"https://login.microsoftonline.com/consumers/oauth2/v2.0",scope:"openid profile offline_access Files.ReadWrite.AppFolder"});
const odB64Url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
async function odChallenge(v){return odB64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))));}
function oneDriveTokens(){try{return JSON.parse(localStorage.getItem(OD_TOKEN_KEY)||"null");}catch{return null;}}
function oneDriveSignedIn(){return Boolean(oneDriveTokens()?.access_token);}
function oneDriveStatus(text,state="offline"){const label=byId("cloudSyncLabel"),sub=byId("cloudSyncState");if(label)label.textContent="OneDrive";if(sub)sub.textContent=text;byId("cloudSyncButton")?.setAttribute("data-state",state);}
async function oneDriveLogin(){const clientId=(byId("oneDriveClientId")?.value||"").trim();if(!clientId)return showToast("Bitte zuerst die Client-ID eintragen.","error");localStorage.setItem(OD_CLIENT_KEY,clientId);const verifier=odB64Url(crypto.getRandomValues(new Uint8Array(48))),state=odB64Url(crypto.getRandomValues(new Uint8Array(18))),challenge=await odChallenge(verifier);sessionStorage.setItem(OD_PKCE_KEY,JSON.stringify({verifier,state}));const c=odConfig(),url=new URL(c.authority+"/authorize");url.search=new URLSearchParams({client_id:c.clientId,response_type:"code",redirect_uri:odRedirect(),response_mode:"query",scope:c.scope,code_challenge:challenge,code_challenge_method:"S256",state}).toString();location.assign(url.toString());}
async function oneDriveHandleCallback(){const q=new URLSearchParams(location.search),code=q.get("code");if(!code)return;const saved=JSON.parse(sessionStorage.getItem(OD_PKCE_KEY)||"null");if(!saved||saved.state!==q.get("state"))throw new Error("Ungültiger Anmeldestatus");const c=odConfig(),body=new URLSearchParams({client_id:c.clientId,grant_type:"authorization_code",code,redirect_uri:odRedirect(),code_verifier:saved.verifier,scope:c.scope});const response=await fetch(c.authority+"/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"OneDrive-Anmeldung fehlgeschlagen");data.obtained_at=Date.now();localStorage.setItem(OD_TOKEN_KEY,JSON.stringify(data));sessionStorage.removeItem(OD_PKCE_KEY);history.replaceState({},"",location.pathname+location.hash);}
async function oneDriveAccessToken(){let token=oneDriveTokens();if(!token)throw new Error("Nicht bei OneDrive angemeldet");if(Date.now()<(token.obtained_at||0)+(Number(token.expires_in||3600)-120)*1000)return token.access_token;if(!token.refresh_token)throw new Error("OneDrive-Anmeldung abgelaufen");const c=odConfig(),body=new URLSearchParams({client_id:c.clientId,grant_type:"refresh_token",refresh_token:token.refresh_token,scope:c.scope});const response=await fetch(c.authority+"/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"OneDrive-Anmeldung abgelaufen");data.refresh_token=data.refresh_token||token.refresh_token;data.obtained_at=Date.now();localStorage.setItem(OD_TOKEN_KEY,JSON.stringify(data));return data.access_token;}
async function odFetch(url,options={}){const headers=new Headers(options.headers||{});headers.set("Authorization","Bearer "+await oneDriveAccessToken());const response=await fetch(url,{...options,headers});if(!response.ok){const text=await response.text();throw new Error(text||`OneDrive-Fehler ${response.status}`);}return response;}
function oneDrivePayload(){return {schemaVersion:3,updatedAt:new Date().toISOString(),members,entries,csvArchive,roleTargets:typeof roleTargets==="object"?roleTargets:{},functionEntryEnabled:typeof functionEntryEnabled==="boolean"?functionEntryEnabled:true};}
function applyOneDrivePayload(data){if(!data||!Array.isArray(data.members)||!Array.isArray(data.entries)||!Array.isArray(data.csvArchive))throw new Error("OneDrive-Datendatei ist ungültig");oneDriveApplying=true;members=data.members;entries=data.entries;csvArchive=data.csvArchive;roleTargets=data.roleTargets||{};functionEntryEnabled=data.functionEntryEnabled!==false;safeStorage.setItem(KEYS.members,JSON.stringify(members));safeStorage.setItem(KEYS.entries,JSON.stringify(entries));safeStorage.setItem(KEYS.archive,JSON.stringify(csvArchive));safeStorage.setItem(KEYS.roleTargets,JSON.stringify(roleTargets));safeStorage.setItem(KEYS.functionEntry,String(functionEntryEnabled));oneDriveApplying=false;render?.();renderAdmin?.();renderArchive?.();}
async function oneDriveReadState(){const response=await odFetch(`https://graph.microsoft.com/v1.0/me/drive/special/approot:/${OD_STATE_FILE}:/content`);return response.json();}
async function oneDriveWriteState(){const data=JSON.stringify(oneDrivePayload());await odFetch(`https://graph.microsoft.com/v1.0/me/drive/special/approot:/${OD_STATE_FILE}:/content`,{method:"PUT",headers:{"Content-Type":"application/json"},body:data});localStorage.setItem("fw_onedrive_last_sync",new Date().toISOString());}
async function syncOneDrive({manual=false}={}){if(!oneDriveSignedIn()||oneDriveBusy||!navigator.onLine)return;oneDriveBusy=true;oneDriveStatus("Synchronisiert","syncing");try{let remote=null;try{remote=await oneDriveReadState();}catch(error){if(!String(error.message).includes("itemNotFound"))console.info("OneDrive-Erstinitialisierung",error);}const localUpdated=localStorage.getItem("fw_onedrive_local_updated")||"";if(remote&&remote.updatedAt>localUpdated)applyOneDrivePayload(remote);else await oneDriveWriteState();oneDriveStatus("Aktuell","online");if(manual)showToast("OneDrive-Daten wurden synchronisiert.");}catch(error){console.error(error);oneDriveStatus("Fehler","error");if(manual)showToast("OneDrive-Synchronisierung fehlgeschlagen.","error");}finally{oneDriveBusy=false;renderOneDriveDialog();}}
function scheduleCloudSync(){if(oneDriveApplying||!oneDriveSignedIn())return;localStorage.setItem("fw_onedrive_local_updated",new Date().toISOString());clearTimeout(oneDriveTimer);oneDriveTimer=setTimeout(()=>syncOneDrive(),900);}
async function oneDriveUploadReport(blob,fileName){const safe=String(fileName||`Bericht-${Date.now()}`).replace(/[\\/:*?"<>|]/g,"-");const folder=safe.toLowerCase().endsWith(".pdf")?"PDF":"CSV";await odFetch(`https://graph.microsoft.com/v1.0/me/drive/special/approot:/Berichte/${folder}/${encodeURIComponent(safe)}:/content`,{method:"PUT",headers:{"Content-Type":blob.type||"application/octet-stream"},body:blob});showToast(`${safe} wurde in OneDrive gespeichert.`);}
function ensureOneDriveUi(){if(byId("cloudSyncButton"))return;const button=document.createElement("button");button.id="cloudSyncButton";button.className="cloud-sync-button";button.type="button";button.innerHTML='<span class="cloud-sync-icon">☁</span><span class="cloud-sync-copy"><b id="cloudSyncLabel">OneDrive</b><small id="cloudSyncState">Einrichten</small></span>';document.body.appendChild(button);const dialog=document.createElement("dialog");dialog.id="cloudSyncDialog";dialog.className="cloud-sync-dialog";dialog.innerHTML='<div class="cloud-sync-shell"><header><div><small>Gemeinsame Datenablage</small><h2>OneDrive-Synchronisierung</h2></div><button type="button" id="cloudSyncClose" class="cloud-sync-close">×</button></header><div class="cloud-sync-body"><p id="oneDriveDetail"></p><label>Microsoft Entra Client-ID<input id="oneDriveClientId" class="text-input" autocomplete="off"></label><p class="cloud-sync-help">Die Anwendung verwendet den OneDrive-App-Ordner „Apps/Feuerwehr Wasser“. Die Client-ID wird nur auf diesem Gerät gespeichert.</p><div class="cloud-sync-actions"><button type="button" class="primary-button" id="oneDriveLogin">Mit Microsoft anmelden</button><button type="button" class="primary-button" id="oneDriveNow">Jetzt synchronisieren</button><button type="button" class="outline-button" id="oneDriveUpload">CSV/PDF nach OneDrive</button><input id="oneDriveUploadFile" type="file" accept=".csv,.pdf,text/csv,application/pdf" hidden><button type="button" class="danger-button" id="oneDriveLogout">Abmelden</button></div></div></div>';document.body.appendChild(dialog);button.onclick=()=>{renderOneDriveDialog();dialog.showModal();};byId("cloudSyncClose").onclick=()=>dialog.close();byId("oneDriveLogin").onclick=oneDriveLogin;byId("oneDriveNow").onclick=()=>syncOneDrive({manual:true});byId("oneDriveLogout").onclick=()=>{localStorage.removeItem(OD_TOKEN_KEY);renderOneDriveDialog();oneDriveStatus("Einrichten","offline");};byId("oneDriveUpload").onclick=()=>byId("oneDriveUploadFile").click();byId("oneDriveUploadFile").onchange=async e=>{for(const file of e.target.files||[])await oneDriveUploadReport(file,file.name);e.target.value="";};}
function renderOneDriveDialog(){const signed=oneDriveSignedIn(),input=byId("oneDriveClientId"),detail=byId("oneDriveDetail");if(input)input.value=localStorage.getItem(OD_CLIENT_KEY)||"";if(detail)detail.textContent=signed?"Verbunden. Mitglieder, Teilnahmen, Einstellungen und Archiv werden zentral in OneDrive gespeichert.":"Client-ID eintragen und anschließend mit dem gemeinsam verwendeten Microsoft-Konto anmelden.";for(const id of ["oneDriveNow","oneDriveUpload","oneDriveLogout"])if(byId(id))byId(id).hidden=!signed;if(byId("oneDriveLogin"))byId("oneDriveLogin").hidden=signed;}
async function initCloudSync(){ensureOneDriveUi();try{await oneDriveHandleCallback();}catch(error){console.error(error);showToast("OneDrive-Anmeldung konnte nicht abgeschlossen werden.","error");}renderOneDriveDialog();if(oneDriveSignedIn()){oneDriveStatus("Verbindet","syncing");await syncOneDrive();setInterval(()=>syncOneDrive(),20000);}else oneDriveStatus("Einrichten","offline");addEventListener("online",()=>syncOneDrive());document.addEventListener("visibilitychange",()=>{if(!document.hidden)syncOneDrive();});}
