"use strict";
const OD_CLIENT_KEY="fw_onedrive_client_id",OD_SHARE_KEY="fw_onedrive_shared_folder_url",OD_TOKEN_KEY="fw_onedrive_tokens",OD_PKCE_KEY="fw_onedrive_pkce",OD_STATE_FILE="feuerwehr-wasser-daten.json";
let oneDriveBusy=false,oneDriveTimer=null,oneDriveApplying=false,oneDriveSharedRoot=null,oneDriveLastError="",oneDriveRetryUntil=0;
const odRedirect=()=>location.origin+location.pathname;
const odConfig=()=>({clientId:localStorage.getItem(OD_CLIENT_KEY)||"",authority:"https://login.microsoftonline.com/consumers/oauth2/v2.0",scope:"openid profile offline_access Files.ReadWrite"});
const odB64Url=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const odShareToken=url=>"u!"+odB64Url(new TextEncoder().encode(url));
async function odChallenge(v){return odB64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))));}
function oneDriveTokens(){try{return JSON.parse(localStorage.getItem(OD_TOKEN_KEY)||"null");}catch{return null;}}
function oneDriveSignedIn(){return Boolean(oneDriveTokens()?.access_token);}
function oneDriveStatus(text,state="offline"){const label=byId("cloudSyncLabel"),sub=byId("cloudSyncState");if(label)label.textContent="OneDrive";if(sub)sub.textContent=text;byId("cloudSyncButton")?.setAttribute("data-state",state);}
function saveOneDriveSettings(){const clientId=(byId("oneDriveClientId")?.value||"").trim(),share=(byId("oneDriveShareUrl")?.value||"").trim();if(clientId)localStorage.setItem(OD_CLIENT_KEY,clientId);if(share)localStorage.setItem(OD_SHARE_KEY,share);else localStorage.removeItem(OD_SHARE_KEY);oneDriveSharedRoot=null;return {clientId,share};}
async function oneDriveLogin(){const {clientId,share}=saveOneDriveSettings();if(!clientId)return showToast("Bitte zuerst die Client-ID eintragen.","error");if(!share)return showToast("Bitte den Link zum gemeinsamen OneDrive-Ordner eintragen.","error");localStorage.removeItem(OD_TOKEN_KEY);const verifier=odB64Url(crypto.getRandomValues(new Uint8Array(48))),state=odB64Url(crypto.getRandomValues(new Uint8Array(18))),challenge=await odChallenge(verifier);sessionStorage.setItem(OD_PKCE_KEY,JSON.stringify({verifier,state}));const c=odConfig(),url=new URL(c.authority+"/authorize");url.search=new URLSearchParams({client_id:c.clientId,response_type:"code",redirect_uri:odRedirect(),response_mode:"query",scope:c.scope,code_challenge:challenge,code_challenge_method:"S256",state,prompt:"consent"}).toString();location.assign(url.toString());}
async function oneDriveHandleCallback(){const q=new URLSearchParams(location.search),code=q.get("code");if(!code)return;const saved=JSON.parse(sessionStorage.getItem(OD_PKCE_KEY)||"null");if(!saved||saved.state!==q.get("state"))throw new Error("Ungültiger Anmeldestatus");const c=odConfig(),body=new URLSearchParams({client_id:c.clientId,grant_type:"authorization_code",code,redirect_uri:odRedirect(),code_verifier:saved.verifier,scope:c.scope});const response=await fetch(c.authority+"/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"OneDrive-Anmeldung fehlgeschlagen");data.obtained_at=Date.now();localStorage.setItem(OD_TOKEN_KEY,JSON.stringify(data));sessionStorage.removeItem(OD_PKCE_KEY);history.replaceState({},"",location.pathname+location.hash);}
async function oneDriveAccessToken(){let token=oneDriveTokens();if(!token)throw new Error("Nicht bei OneDrive angemeldet");if(Date.now()<(token.obtained_at||0)+(Number(token.expires_in||3600)-120)*1000)return token.access_token;if(!token.refresh_token)throw new Error("OneDrive-Anmeldung abgelaufen");const c=odConfig(),body=new URLSearchParams({client_id:c.clientId,grant_type:"refresh_token",refresh_token:token.refresh_token,scope:c.scope});const response=await fetch(c.authority+"/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"OneDrive-Anmeldung abgelaufen");data.refresh_token=data.refresh_token||token.refresh_token;data.obtained_at=Date.now();localStorage.setItem(OD_TOKEN_KEY,JSON.stringify(data));return data.access_token;}
async function odFetch(url,options={},retry=true){
  const wait=Math.max(0,oneDriveRetryUntil-Date.now());
  if(wait)await new Promise(resolve=>setTimeout(resolve,wait));
  const headers=new Headers(options.headers||{});
  headers.set("Authorization","Bearer "+await oneDriveAccessToken());
  const response=await fetch(url,{...options,headers});
  if(response.status===429&&retry){
    const seconds=Math.max(1,Number.parseInt(response.headers.get("Retry-After")||"5",10)||5);
    oneDriveRetryUntil=Date.now()+seconds*1000;
    await new Promise(resolve=>setTimeout(resolve,seconds*1000));
    return odFetch(url,options,false);
  }
  if(!response.ok){const text=await response.text();throw new Error(text||`OneDrive-Fehler ${response.status}`);}
  return response;
}
async function oneDriveResolveSharedRoot(){if(oneDriveSharedRoot)return oneDriveSharedRoot;const share=localStorage.getItem(OD_SHARE_KEY)||"";if(!share)throw new Error("Kein gemeinsamer OneDrive-Ordner eingerichtet");const response=await odFetch(`https://graph.microsoft.com/v1.0/shares/${odShareToken(share)}/driveItem?$select=id,name,parentReference,folder,remoteItem`,{headers:{Prefer:"redeemSharingLink"}});const item=await response.json(),resolved=item.remoteItem||item,driveId=resolved.parentReference?.driveId||item.parentReference?.driveId,id=resolved.id||item.id;if(!driveId||!id||!resolved.folder&&!item.folder)throw new Error("Der Freigabelink verweist nicht auf einen zugänglichen Ordner");oneDriveSharedRoot={driveId,id,name:resolved.name||item.name||"Gemeinsamer Ordner"};return oneDriveSharedRoot;}
const odItemBase=(root=oneDriveSharedRoot)=>`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(root.driveId)}/items/${encodeURIComponent(root.id)}`;
function oneDrivePayload(){return {schemaVersion:3,updatedAt:new Date().toISOString(),members,entries,csvArchive,roleTargets:typeof getRoleTargets==="function"?getRoleTargets():{},functionEntryEnabled:typeof isFunctionEntryEnabled==="function"?isFunctionEntryEnabled():true};}
function applyOneDrivePayload(data){if(!data||!Array.isArray(data.members)||!Array.isArray(data.entries)||!Array.isArray(data.csvArchive))throw new Error("OneDrive-Datendatei ist ungültig");oneDriveApplying=true;members=data.members;entries=data.entries;csvArchive=data.csvArchive;const importedRoleTargets=data.roleTargets||{};const importedFunctionEntryEnabled=data.functionEntryEnabled!==false;safeStorage.setItem(KEYS.members,JSON.stringify(members));safeStorage.setItem(KEYS.entries,JSON.stringify(entries));safeStorage.setItem(KEYS.archive,JSON.stringify(csvArchive));if(typeof saveRoleTargets==="function")saveRoleTargets(importedRoleTargets);else safeStorage.setItem(KEYS.roleTargets,JSON.stringify(importedRoleTargets));safeStorage.setItem(KEYS.functionEntry,String(importedFunctionEntryEnabled));oneDriveApplying=false;if(typeof renderMembers==="function")renderMembers();if(typeof renderToday==="function")renderToday();if(typeof renderAdmin==="function")renderAdmin();if(typeof renderArchive==="function")renderArchive();if(typeof renderStatistics==="function")renderStatistics();}
async function oneDriveReadState(){const root=await oneDriveResolveSharedRoot(),response=await odFetch(`${odItemBase(root)}:/${encodeURIComponent(OD_STATE_FILE)}:/content`);return response.json();}
async function oneDriveWriteState(){const root=await oneDriveResolveSharedRoot(),data=JSON.stringify(oneDrivePayload());await odFetch(`${odItemBase(root)}:/${encodeURIComponent(OD_STATE_FILE)}:/content`,{method:"PUT",headers:{"Content-Type":"application/json"},body:data});localStorage.setItem("fw_onedrive_last_sync",new Date().toISOString());}
async function odEnsureFolder(parentId,name){const root=await oneDriveResolveSharedRoot(),list=await odFetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(root.driveId)}/items/${encodeURIComponent(parentId)}/children?$select=id,name,folder`),data=await list.json(),existing=(data.value||[]).find(x=>x.folder&&x.name===name);if(existing)return existing.id;const response=await odFetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(root.driveId)}/items/${encodeURIComponent(parentId)}/children`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,folder:{},"@microsoft.graph.conflictBehavior":"fail"})});return (await response.json()).id;}
async function syncOneDrive({manual=false}={}){if(!oneDriveSignedIn()||oneDriveBusy||!navigator.onLine)return;oneDriveBusy=true;oneDriveStatus("Synchronisiert","syncing");try{let remote=null;try{remote=await oneDriveReadState();}catch(error){if(!String(error.message).includes("itemNotFound"))throw error;}const localUpdated=localStorage.getItem("fw_onedrive_local_updated")||"";if(remote&&remote.updatedAt>localUpdated)applyOneDrivePayload(remote);else await oneDriveWriteState();oneDriveLastError="";oneDriveStatus("Aktuell","online");if(manual)showToast("Daten im gemeinsamen OneDrive-Ordner wurden synchronisiert.");}catch(error){console.error(error);oneDriveLastError=String(error.message||error);oneDriveStatus("Fehler","error");const detail=byId("oneDriveDetail");if(detail)detail.textContent=`Fehler: ${oneDriveLastError}`;if(manual)showToast("OneDrive-Synchronisierung fehlgeschlagen. Details stehen im OneDrive-Fenster.","error");}finally{oneDriveBusy=false;renderOneDriveDialog();}}
function scheduleCloudSync(){if(oneDriveApplying||!oneDriveSignedIn())return;localStorage.setItem("fw_onedrive_local_updated",new Date().toISOString());clearTimeout(oneDriveTimer);oneDriveTimer=setTimeout(()=>syncOneDrive(),900);}
async function oneDriveUploadReport(blob,fileName){const root=await oneDriveResolveSharedRoot(),reportsId=await odEnsureFolder(root.id,"Berichte"),folderName=String(fileName||"").toLowerCase().endsWith(".pdf")?"PDF":"CSV",folderId=await odEnsureFolder(reportsId,folderName),safe=String(fileName||`Bericht-${Date.now()}`).replace(/[\\/:*?"<>|]/g,"-");await odFetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(root.driveId)}/items/${encodeURIComponent(folderId)}:/${encodeURIComponent(safe)}:/content`,{method:"PUT",headers:{"Content-Type":blob.type||"application/octet-stream"},body:blob});showToast(`${safe} wurde im gemeinsamen OneDrive-Ordner gespeichert.`);}
function ensureOneDriveUi(){if(byId("cloudSyncButton"))return;const button=document.createElement("button");button.id="cloudSyncButton";button.className="cloud-sync-button";button.type="button";button.innerHTML='<span class="cloud-sync-icon">☁</span><span class="cloud-sync-copy"><b id="cloudSyncLabel">OneDrive</b><small id="cloudSyncState">Einrichten</small></span>';document.body.appendChild(button);const dialog=document.createElement("dialog");dialog.id="cloudSyncDialog";dialog.className="cloud-sync-dialog";dialog.innerHTML='<div class="cloud-sync-shell"><header><div><small>Gemeinsame Datenablage</small><h2>OneDrive-Synchronisierung</h2></div><button type="button" id="cloudSyncClose" class="cloud-sync-close">×</button></header><div class="cloud-sync-body"><p id="oneDriveDetail"></p><label>Microsoft Entra Client-ID<input id="oneDriveClientId" class="text-input" autocomplete="off"></label><label>Link zum gemeinsamen OneDrive-Ordner<input id="oneDriveShareUrl" class="text-input" type="url" inputmode="url" autocomplete="off" placeholder="Freigabelink hier einfügen"></label><p class="cloud-sync-help">Der Link bleibt auf diesem Gerät. Das angemeldete Microsoft-Konto benötigt Bearbeitungszugriff auf den freigegebenen Ordner.</p><div class="cloud-sync-actions"><button type="button" class="primary-button" id="oneDriveLogin">Einstellungen speichern und mit Microsoft anmelden</button><button type="button" class="primary-button" id="oneDriveNow">Jetzt synchronisieren</button><button type="button" class="danger-button" id="oneDriveLogout">Abmelden</button></div></div></div>';document.body.appendChild(dialog);button.onclick=()=>{renderOneDriveDialog();dialog.showModal();};byId("cloudSyncClose").onclick=()=>dialog.close();byId("oneDriveLogin").onclick=oneDriveLogin;byId("oneDriveNow").onclick=()=>{saveOneDriveSettings();syncOneDrive({manual:true});};byId("oneDriveLogout").onclick=()=>{localStorage.removeItem(OD_TOKEN_KEY);oneDriveSharedRoot=null;renderOneDriveDialog();oneDriveStatus("Einrichten","offline");};}
function renderOneDriveDialog(){const signed=oneDriveSignedIn(),client=byId("oneDriveClientId"),share=byId("oneDriveShareUrl"),detail=byId("oneDriveDetail");if(client)client.value=localStorage.getItem(OD_CLIENT_KEY)||"";if(share)share.value=localStorage.getItem(OD_SHARE_KEY)||"";if(detail)detail.textContent=oneDriveLastError?`Fehler: ${oneDriveLastError}`:(signed?"Verbunden. Mitglieder, Teilnahmen, Einstellungen und Archiv werden im gemeinsamen OneDrive-Ordner gespeichert.":"Client-ID und Freigabelink eintragen, danach mit einem Microsoft-Konto mit Bearbeitungszugriff anmelden.");for(const id of ["oneDriveNow","oneDriveLogout"])if(byId(id))byId(id).hidden=!signed;if(byId("oneDriveLogin"))byId("oneDriveLogin").hidden=signed;}
async function initCloudSync(){ensureOneDriveUi();try{await oneDriveHandleCallback();}catch(error){console.error(error);showToast("OneDrive-Anmeldung konnte nicht abgeschlossen werden.","error");}renderOneDriveDialog();if(oneDriveSignedIn()){oneDriveStatus("Verbindet","syncing");await syncOneDrive();}else oneDriveStatus("Einrichten","offline");addEventListener("online",()=>syncOneDrive());document.addEventListener("visibilitychange",()=>{if(!document.hidden)syncOneDrive();});}
