'use strict';
(function(){
 const by=id=>document.getElementById(id);let busy=false;
 const validOrigin=value=>{try{const u=new URL(value);return u.protocol==='https:'&&/^[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev$/.test(u.hostname)&&!u.port&&!u.username&&!u.password&&u.pathname==='/'&&!u.search&&!u.hash;}catch{return false;}};
 function access(){const p=new URLSearchParams(location.hash.slice(1));const origin=p.get('p'),capability=p.get('c'),alias=p.get('a');if(!validOrigin(origin)||!/^[A-Za-z0-9_-]{43}$/.test(capability||'')||!/^[a-f0-9]{32}$/.test(alias||''))return null;return {origin,capability,alias};}
 async function api(c,path,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const res=await fetch(c.origin+path,{method:'POST',headers:{Authorization:'Bearer '+c.capability,'Content-Type':'application/json'},body:JSON.stringify(data),cache:'no-store',redirect:'error',signal:controller.signal});const value=await res.json();if(!res.ok)throw new Error(value.error||'Erinnerungen konnten nicht eingerichtet werden.');return value;}finally{clearTimeout(timer);}}
 async function registration(){const r=await navigator.serviceWorker.register('service-worker.js');await navigator.serviceWorker.ready;return r;}
 function controls(){by('pushEnable').disabled=busy;by('pushDisable').disabled=busy;}
 async function refresh(){const c=access();by('pushSection').hidden=false;by('pushEnable').hidden=!c;by('pushEnable').textContent='Erinnerungen erlauben';by('pushDisable').hidden=true;if(!c){by('pushStatus').textContent='Für Handy-Erinnerungen den persönlichen QR-Code am Gerätehaus-iPad nach der Einrichtung erneut scannen.';return;}const ios=/iPhone|iPad|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;if(ios&&!navigator.standalone&&!matchMedia('(display-mode: standalone)').matches){by('pushEnable').disabled=true;by('pushStatus').textContent='Auf dem iPhone: Teilen → Zum Home-Bildschirm. Den Deckel danach über das neue Symbol öffnen und Erinnerungen erlauben.';return;}if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window)){by('pushEnable').disabled=true;by('pushStatus').textContent='Dieser Browser unterstützt keine Handy-Erinnerungen.';return;}by('pushEnable').disabled=false;try{const saved=await DeckelDevice.read();if(saved){by('pushDisable').hidden=false;by('pushEnable').hidden=Boolean(saved.registered&&saved.capability===c.capability&&Notification.permission==='granted');by('pushStatus').textContent=Notification.permission==='granted'?(saved.registered?'Erinnerungen auf diesem Handy gespeichert. Die Verwaltung versendet sie manuell.':'Einrichtung noch nicht bestätigt. Bitte Erinnerungen erneut erlauben.'):'Erinnerungen sind in den Handy-Einstellungen blockiert.';}else by('pushStatus').textContent='Freiwillig aktivieren. Dein persönlicher Zugang wird dafür auf diesem Handy gespeichert. Technische Geräte-Adressen werden bei Cloudflare hinterlegt.';}catch{by('pushStatus').textContent='Erinnerungen benötigen freigegebenen Gerätespeicher.';}}
 async function enable(){if(busy)return;const c=access();if(!c)return;busy=true;controls();by('pushStatus').textContent='Erinnerungen werden eingerichtet …';try{
  // Request permission directly in the member's click, before network waits.
  const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Benachrichtigungen nicht erlaubt. Du kannst sie in den Handy-Einstellungen freigeben.');
  const res=await fetch(c.origin+'/health',{cache:'no-store',credentials:'omit',redirect:'error'});if(!res.ok)throw new Error('Erinnerungsdienst derzeit nicht erreichbar.');const info=await res.json();if(!/^[A-Za-z0-9_-]{87}$/.test(info.publicKey||''))throw new Error('Push-Schlüssel ungültig.');
  const reg=await registration(),old=await DeckelDevice.read();if(old&&old.alias!==c.alias)throw new Error('Dieses Handy ist bereits mit einem anderen Deckel verknüpft. Bitte dort zuerst Erinnerungen deaktivieren.');
  const key=Uint8Array.from(atob(info.publicKey.replace(/-/g,'+').replace(/_/g,'/')),x=>x.charCodeAt(0));const subscription=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});
  // Persist the click target before registering it remotely. No personal URL crosses the network.
  await DeckelDevice.write({url:location.href,alias:c.alias,origin:c.origin,capability:c.capability,endpoint:subscription.endpoint,registered:false});
  await api(c,'/subscribe',{alias:c.alias,endpoint:subscription.endpoint});await DeckelDevice.write({url:location.href,alias:c.alias,origin:c.origin,capability:c.capability,endpoint:subscription.endpoint,registered:true});by('pushStatus').textContent='Erinnerungen aktiviert. Du erhältst sie, wenn die Verwaltung eine Erinnerung sendet.';by('pushDisable').hidden=false;by('pushEnable').hidden=true;
 }catch(error){by('pushStatus').textContent=error.message||'Einrichtung fehlgeschlagen. Bitte erneut versuchen.';}finally{busy=false;controls();}}
 async function disable(){if(busy)return;busy=true;controls();try{const saved=await DeckelDevice.read();if(saved){try{await api(saved,'/unsubscribe',{alias:saved.alias,endpoint:saved.endpoint});}catch{/* Unsubscribing locally revokes the push endpoint even if the server is offline. */}}const reg=await navigator.serviceWorker.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub&&!await sub.unsubscribe())throw new Error('Abmeldung nicht bestätigt. Bitte erneut versuchen.');await DeckelDevice.clear();by('pushDisable').hidden=true;by('pushEnable').hidden=false;by('pushStatus').textContent='Erinnerungen auf diesem Handy deaktiviert. Gespeicherter Zugang entfernt.';}catch(error){by('pushStatus').textContent=error.message;}finally{busy=false;controls();}}
 async function restore(){if(location.hash)return;try{const saved=await DeckelDevice.read();if(saved)history.replaceState(null,'',saved.url);}catch{}}
 by('pushEnable').onclick=enable;by('pushDisable').onclick=disable;window.DeckelPush={restore,refresh};addEventListener('hashchange',refresh);restore().then(refresh);
})();
