/* Personal phone menu. Money and points change only after the iPad confirms OneDrive. */
(function(g){
 'use strict';const $=id=>document.getElementById(id);let data=null,record=null,draft=[],pending=null,busy=false,timer=null,epoch=0,service=null;
 const money=c=>(c/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'}),points=n=>(n/150).toLocaleString('de-DE');
 const originOK=value=>{try{const u=new URL(value);return u.protocol==='https:'&&/^[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev$/.test(u.hostname)&&u.origin===value;}catch{return false;}};
 function controls(){const blocked=busy||!!pending||!service;for(const id of ['phone-beer','phone-wine','phone-points-beer','phone-points-wine','phone-cash-submit','phone-undo'])$(id).disabled=blocked;const used=draft.reduce((n,x)=>n+(x.pointUnits||0),0);$('phone-points-beer').disabled=blocked||!data||data.pointUnits-used<data.beerUnits;$('phone-points-wine').disabled=blocked||!data||data.pointUnits-used<data.wineUnits;$('phone-save').disabled=blocked||!draft.length;$('phone-discard').disabled=busy||!!pending||!draft.length;$('phone-undo').hidden=!data?.undo;$('phone-undo').disabled=blocked||draft.length>0;$('phone-cash-submit').disabled=blocked||draft.length>0;$('phone-summary').textContent=draft.length?draft.length+' Getränke vorgemerkt'+(used?' · '+points(used)+' Treuepunkte':'')+' · Noch nicht gespeichert.':'';$('phone-retry').hidden=!pending;$('phone-retry').disabled=busy;$('phone-retired').hidden=!pending||!service||pending.revision===service.revision;$('phone-retired').disabled=busy;}
 async function api(path,body,svc=service){if(!svc||!originOK(svc.origin))throw Error('Buchungsdienst noch nicht eingerichtet.');const response=await fetch(svc.origin+path,{method:'POST',headers:{Authorization:'Bearer '+svc.capability,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',credentials:'omit',redirect:'error',signal:AbortSignal.timeout(20000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Verbindung nicht bestätigt. Bitte erneut prüfen.');return result;}
 async function persist(){await g.DeckelDevice.saveCommand(record.alias,pending);}
 function later(){clearTimeout(timer);if(pending&&!document.hidden)timer=setTimeout(check,15000);}
 async function check(){if(busy||!pending||!service||document.hidden)return;const version=epoch,job=pending,rec=record,svc=service;busy=true;controls();
  try{let result=await api('/commands/status',{alias:rec.alias,revision:job.revision,id:job.id},svc);if(result.status==='missing')result=await api('/commands/submit',{alias:rec.alias,revision:job.revision,id:job.id,envelope:job.envelope},svc);if(version!==epoch)return;
   if(result.status==='done'){pending=null;await persist();$('phone-status').textContent='✓ Vom Gerätehaus-iPad übernommen und gespeichert. Kontostand wird aktualisiert.';g.DeckelReload?.();}
   else if(result.status==='rejected'){pending=null;await persist();$('phone-status').textContent=result.result==='pointsChanged'?'Nicht gespeichert: Treuepunkte oder Punktekosten haben sich geändert. Bitte aktualisieren und neu eingeben.':result.result==='correctionChanged'?'Nicht gespeichert: Der Eintrag wurde inzwischen bezahlt, geändert oder ist nicht mehr von heute.':'Nicht gespeichert. Bitte den Handyzugang am Gerätehaus-iPad prüfen.';}
   else $('phone-status').textContent='⏳ Wartet auf Synchronisierung mit dem Gerätehaus-iPad. Noch nicht im Kontostand enthalten.';
  }catch(e){if(version===epoch)$('phone-status').textContent=e.message+' Der Vorgang bleibt erhalten. Mit „Status erneut prüfen“ dieselbe Buchung prüfen.';}
  finally{if(version===epoch){busy=false;controls();later();}}
 }
 async function submit(command){if(busy||pending||!record||!service)return;if(command.kind!=='drinks'&&draft.length){$('phone-status').textContent='Bitte die vorgemerkten Getränke zuerst senden oder entfernen.';return;}const version=epoch;busy=true;controls();try{g.DeckelCommands.validate(command);const id=crypto.randomUUID(),envelope=await g.DeckelCommands.seal(command,record,id);if(version!==epoch)return;pending={id,revision:service.revision,envelope};await persist();draft=[];$('phone-status').textContent='Vorgang sicher vorgemerkt. Übertragung wird geprüft …';}catch(e){pending=null;$('phone-status').textContent=e.message;}finally{if(version===epoch){busy=false;controls();if(pending)check();}}}
 async function render(snapshot){const p=new URLSearchParams(location.hash.slice(1)),next={version:1,alias:p.get('a'),key:p.get('k')},changed=record?.alias!==next.alias||record?.key!==next.key;if(changed){epoch++;clearTimeout(timer);draft=[];pending=null;busy=false;record=next;}data=snapshot;service=snapshot.actions&&originOK(snapshot.actions.origin)&&/^[A-Za-z0-9_-]{43}$/.test(snapshot.actions.capability||'')?snapshot.actions:null;
  $('phone-menu').hidden=false;$('phone-setup').hidden=!!service;$('phone-points-beer').textContent='🍺 Bier für '+points(snapshot.beerUnits||150)+((snapshot.beerUnits||150)===150?' Punkt':' Punkte');$('phone-points-wine').textContent='🍷 Wein für '+points(snapshot.wineUnits||150)+((snapshot.wineUnits||150)===150?' Punkt':' Punkte');if(changed){const version=epoch;try{const saved=await g.DeckelDevice.readCommand(record.alias);if(version!==epoch)return;pending=saved;}catch{$('phone-status').textContent='Gerätespeicher nicht verfügbar. Eingaben können nicht sicher vorgemerkt werden.';service=null;}}controls();if(pending)check();
 }
 function add(drink,usePoints){if(busy||pending||!service||draft.length>=20)return;const cost=drink==='wine'?data.wineUnits:data.beerUnits;if(usePoints&&data.pointUnits-draft.reduce((n,x)=>n+(x.pointUnits||0),0)<cost)return;draft.push({drink,...(usePoints?{pointUnits:cost}:{})});controls();}
 function init(){g.addEventListener('beforeunload',e=>{if(draft.length){e.preventDefault();e.returnValue='';}});for(const [id,drink,use] of [['phone-beer','beer',false],['phone-wine','wine',false],['phone-points-beer','beer',true],['phone-points-wine','wine',true]])$(id).onclick=()=>add(drink,use);$('phone-save').onclick=()=>submit({version:1,kind:'drinks',entries:draft.slice()});$('phone-discard').onclick=()=>{draft.pop();controls();};$('phone-retry').onclick=check;$('phone-retired').onclick=async()=>{if(busy||!pending||!service||pending.revision===service.revision)return;if(!confirm('Der Handyzugang wurde ersetzt. Bitte zuerst am iPad prüfen, ob dieser Vorgang bereits gebucht wurde. Nur die alte Vormerkung auf diesem Handy entfernen? Gespeicherte Buchungen bleiben erhalten.'))return;busy=true;controls();try{await g.DeckelDevice.saveCommand(record.alias,null);pending=null;$('phone-status').textContent='Alte Vormerkung entfernt. Bereits gespeicherte Einträge bleiben auf dem Konto.';}catch(e){$('phone-status').textContent=e.message;}finally{busy=false;controls();}};$('phone-undo').onclick=()=>{if(data?.undo&&confirm('Diesen letzten vollständig unbezahlten Eintrag zurücknehmen? Das iPad prüft die Rücknahme vor dem Speichern.'))submit({version:1,kind:'undo',targetId:data.undo.targetId});};$('phone-cash-form').onsubmit=e=>{e.preventDefault();const raw=$('phone-amount').value.trim().replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(raw)){$('phone-status').textContent='Bitte einen gültigen Geldbetrag eingeben.';return;}const cents=Math.round(Number(raw)*100);if(!$('phone-cash-confirm').checked){$('phone-status').textContent='Bitte zuerst bestätigen, dass das Geld in der Kasse liegt.';return;}if(confirm(money(cents)+' tatsächlich in die Getränkekasse gelegt?'))submit({version:1,kind:'cash',cents});};}
 g.DeckelActions={render};document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(timer);}else if(pending)check();});g.addEventListener('hashchange',()=>{epoch++;clearTimeout(timer);record=null;data=null;service=null;pending=null;draft=[];busy=false;$('phone-menu').hidden=true;});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(globalThis);
