/* Admin credentials stay in private OneDrive. No automatic reminders. */
(function(global){
 'use strict';const S=global.DrinksStore;
 const validOrigin=value=>{try{const u=new URL(value);return u.protocol==='https:'&&/^[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev$/.test(u.hostname)&&!u.port&&!u.username&&!u.password&&u.pathname==='/'&&!u.search&&!u.hash;}catch{return false;}};
 const admin=()=>{if(!adminUnlocked)throw new Error('Bitte zuerst die Administration entsperren.');};
 async function config(){return (await S.readMobileFile('push-verbindung.json'))?.data||null;}
 async function request(c,path,data){if(!validOrigin(c.origin)||!/^[a-f0-9]{64}$/.test(c.token))throw new Error('Erinnerungs-Verbindung ungültig.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);try{const response=await fetch(c.origin+path,{method:'POST',headers:{Authorization:'Bearer '+c.token,'Content-Type':'application/json'},body:JSON.stringify(data),cache:'no-store',redirect:'error',signal:controller.signal});const value=await response.json();if(!response.ok)throw Object.assign(new Error(value.error||'Erinnerungsdienst nicht erreichbar.'),{status:response.status});return value;}finally{clearTimeout(timer);}}
 async function connect(origin,token){admin();origin=origin.trim().replace(/\/$/,'');const c={version:1,origin,token:token.trim()};const result=await request(c,'/admin/check',{});if(!/^[A-Za-z0-9_-]{87}$/.test(result.publicKey||''))throw new Error('Push-Schlüssel des Dienstes ungültig.');admin();const old=await S.readMobileFile('push-verbindung.json');if(old&&old.data.origin!==origin)throw new Error('Ein anderer Dienst würde bestehende Erinnerungszugänge trennen. Bitte den bisherigen Dienst verwenden.');await S.writeMobileFile('push-verbindung.json',c,old?.item?.eTag);return origin;}
 async function prepare(record){const c=await config();if(!c)return null;const result=await request(c,'/admin/account',{alias:record.alias,revision:record.revision});if(!/^[A-Za-z0-9_-]{43}$/.test(result.capability||''))throw new Error('Erinnerungszugang konnte nicht erstellt werden.');return {origin:c.origin,capability:result.capability};}
 async function status(id){admin();const c=await config();if(!c)return {configured:false};const saved=await S.readMobileFile(await S.mobileFileName(id));if(!saved)return {configured:true,devices:0};let result;try{result=await request(c,'/admin/status',{alias:saved.data.alias});}catch(error){if(error.status===404)return {configured:true,devices:0};throw error;}admin();return {configured:true,...result};}
 async function send(id,requestId){admin();const c=await config();if(!c)throw new Error('Bitte zuerst unter Getränkeverwaltung → Handy-Erinnerungen den Versanddienst verbinden.');const account=await S.read(id);if(global.DrinksModel.totals(account).balance<=0)throw new Error('Der Deckel ist bereits bezahlt. Keine Erinnerung versendet.');const saved=await S.readMobileFile(await S.mobileFileName(id));if(!saved)throw new Error('Das Mitglied muss zuerst seinen persönlichen Handy-Deckel einrichten.');await global.DrinksMobile.publish(id);admin();const fresh=await S.read(id);if(global.DrinksModel.totals(fresh).balance<=0)throw new Error('Der Deckel ist inzwischen bezahlt. Keine Erinnerung versendet.');return request(c,'/admin/send',{alias:saved.data.alias,requestId});}
 async function loadSetup(){if(!adminUnlocked)return;const status=byId('pushSetupStatus');try{const c=await config();if(!adminUnlocked)return;status.textContent=c?'Verbunden: '+c.origin+'. Versand erfolgt ausschließlich manuell.':'Noch kein Versanddienst verbunden. Der kostenlose Cloudflare-Dienst muss einmalig bereitgestellt werden.';}catch{status.textContent='Zum Laden der Verbindung bitte OneDrive verbinden.';}}
 function init(){const view=document.createElement('section');view.id='settingsPushView';view.className='view settings-view';view.hidden=true;view.innerHTML='<div class="screen-heading"><div><p class="eyebrow">Getränkeverwaltung</p><h2>Handy-Erinnerungen</h2><p>Erinnerungen einzeln und bewusst versenden.</p></div><button class="outline-button" data-back type="button">Zurück zur Getränkeverwaltung</button></div><article class="panel"><h3>Kostenlosen Versanddienst verbinden</h3><p>Cloudflare Workers und D1 ausschließlich im Free-Tarif verwenden. Ohne Verbindung werden keine Handy-Benachrichtigungen versendet.</p><p>Der Dienst speichert technische Geräte-Adressen und zufällige Kontokennungen. Namen, Beträge, PINs und Deckel-Schlüssel werden nicht übertragen. Die Mitglieder erlauben Erinnerungen freiwillig und können sie wieder deaktivieren.</p><p><a href="https://github.com/ffw-wasser/home/blob/main/cloudflare/push/README.md" target="_blank" rel="noopener noreferrer">Einrichtung Schritt für Schritt</a></p><form id="pushConnectForm"><label for="pushOrigin">Cloudflare-Dienst-Adresse</label><input id="pushOrigin" class="text-input" type="url" placeholder="https://feuerwehr-wasser-deckel-push.DEIN-KONTO.workers.dev" autocomplete="off" required><label for="pushAdminToken">Admin-Versandzugang</label><input id="pushAdminToken" class="text-input" type="password" minlength="64" maxlength="64" autocomplete="off" required><button class="primary-button" type="submit">Verbindung prüfen und in OneDrive speichern</button></form><p id="pushSetupStatus" role="status"></p><p>Mitglieder scannen nach der Einrichtung ihren QR-Code noch einmal, fügen den Deckel zum Home-Bildschirm hinzu und tippen auf „Erinnerungen erlauben“. Danach bleibt der Zugang gespeichert.</p></article>';document.querySelector('main.app-shell').append(view);view.querySelector('[data-back]').onclick=()=>{byId('pushAdminToken').value='';showView('settingsDrinksView');};new MutationObserver(()=>{if(view.hidden)byId('pushAdminToken').value='';}).observe(view,{attributes:true,attributeFilter:['hidden']});const button=document.createElement('button');button.className='primary-button';button.type='button';button.textContent='Erinnerungen einrichten';button.onclick=()=>{if(showView('settingsPushView')!==false)loadSetup();};byId('drinksSettingsPushCard').append(button);byId('pushConnectForm').onsubmit=async event=>{event.preventDefault();if(!adminUnlocked)return;const button=event.submitter||view.querySelector('button[type="submit"]'),token=byId('pushAdminToken').value;byId('pushAdminToken').value='';button.disabled=true;byId('pushSetupStatus').textContent='Verbindung wird geprüft …';try{await connect(byId('pushOrigin').value,token);await loadSetup();}catch(error){byId('pushSetupStatus').textContent=error.message;}finally{button.disabled=false;}};}
 global.DrinksPush={connect,prepare,status,send,loadSetup,validOrigin};
 if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();}
})(typeof window==='undefined'?globalThis:window);
