let documentReportPages=[];
let documentReportReady=false;
let pendingDocumentReport=null;
function resetDocumentReportState(){documentReportPages.forEach(page=>{if(page.url)URL.revokeObjectURL(page.url);});documentReportPages=[];documentReportReady=false;pendingDocumentReport=null;manualCropGesture=null;if(manualCropState?.bitmap)manualCropState.bitmap.close?.();manualCropState=null;const cropDialog=byId("manualDocumentCropDialog");if(cropDialog?.open)cropDialog.close();const panel=byId("documentReportPanel");if(panel){panel.hidden=true;const pages=byId("documentReportPages");if(pages)pages.innerHTML="";const status=byId("documentReportStatus");if(status)status.textContent="Noch keine Seite aufgenommen.";}}
function hasActiveAtue(){
  if(sessionType==="Allgemeine Probe")return Boolean(breathingProtectionPlanned&&currentAtueMember);
  if(sessionType==="Einsatz")return Boolean(byId("opAtueUsed")?.checked&&!byId("opAtueDepartment")?.checked&&String(byId("opAtuePerson")?.value||"").trim());
  return false;
}
function documentReportRequired(){return sessionType==="Ausschuss Sitzung"||hasActiveAtue();}
function documentReportKind(){return sessionType==="Ausschuss Sitzung"?"Sitzungsbericht":"Bericht Atemschutzüberwachung";}
function hideDocumentReportUi(){
  const panel=byId("documentReportPanel");
  if(panel){panel.hidden=true;panel.style.display="none";panel.setAttribute("aria-hidden","true");}
  window.closeIpadDocumentEditor?.();
  const cropDialog=byId("manualDocumentCropDialog");
  if(cropDialog?.open){try{cropDialog.close();}catch{cropDialog.removeAttribute("open");}}
}
function syncDocumentReportVisibility(stage=homeFlowStage){
  const panel=byId("documentReportPanel");
  if(!panel)return;
  const visible=stage===3 && documentReportRequired() && !documentReportReady;
  panel.hidden=!visible;
  panel.style.display=visible?"block":"none";
  panel.setAttribute("aria-hidden",String(!visible));
}

function documentReportSubtitle(){return sessionType==="Ausschuss Sitzung"?"Formular fotografieren oder auswählen. Jede Seite wird automatisch zugeschnitten und als PDF gespeichert.":sessionType==="Einsatz"?`Einsatz-ATÜ: ${byId("opAtuePerson")?.value||"noch nicht ausgewählt"}. Formular fotografieren, prüfen und als zugeschnittenes PDF speichern.`:`ATÜ: ${currentAtueMember?nameForTile(currentAtueMember):"nicht besetzt"}. Formular fotografieren, prüfen und als zugeschnittenes PDF speichern.`;}
function ensureDocumentReportPanel(){
 let panel=byId("documentReportPanel");if(panel)return panel;
 panel=document.createElement("section");panel.id="documentReportPanel";panel.className="panel document-report-panel";panel.hidden=true;
 panel.innerHTML=`<div class="panel-heading"><span class="step yellow">DOK</span><div><h3 id="documentReportTitle">Dokumentbericht</h3><p id="documentReportSubtitle"></p></div></div><div class="document-report-actions"><label class="primary-button camera-button">Seite fotografieren<input id="documentReportCamera" type="file" accept="image/*" capture="environment" multiple></label><label class="outline-button">Bild auswählen<input id="documentReportFiles" type="file" accept="image/*" multiple></label></div><p class="document-report-help">Das Bild wird automatisch an den hellen Außenrändern zugeschnitten. Bitte das Formular möglichst gerade und vollständig fotografieren.</p><p class="document-report-status" id="documentReportStatus">Noch keine Seite aufgenommen.</p><div class="document-report-pages" id="documentReportPages"></div><div class="document-report-finish"><button class="primary-button" id="documentReportContinue" type="button">Zugeschnittenes PDF übernehmen</button></div>`;
 const target=byId("homeStageFinish")||byId("tacticsView")||byId("attendanceView");target.insertAdjacentElement("beforebegin",panel);
 const add=async files=>{for(const file of [...files]){if(!file.type.startsWith("image/"))continue;const cropped=await cropDocumentImage(file);documentReportPages.push({id:makeId(),file,blob:cropped.blob,url:URL.createObjectURL(cropped.blob),width:cropped.width,height:cropped.height,crop:cropped.crop});}documentReportReady=false;renderDocumentReportPages();};
 byId("documentReportCamera").onchange=async event=>{await add(event.target.files);event.target.value="";};
 byId("documentReportFiles").onchange=async event=>{await add(event.target.files);event.target.value="";};
 byId("documentReportPages").onclick=event=>{const button=event.target.closest("button[data-page-action]");if(!button)return;const index=documentReportPages.findIndex(page=>page.id===button.dataset.pageId);if(index<0)return;const action=button.dataset.pageAction;if(action==="crop"){(window.openIpadDocumentCrop||window.openManualDocumentCrop||openManualDocumentCrop)(index);return;}if(action==="delete"){URL.revokeObjectURL(documentReportPages[index].url);documentReportPages.splice(index,1);}else if(action==="up"&&index>0)[documentReportPages[index-1],documentReportPages[index]]=[documentReportPages[index],documentReportPages[index-1]];else if(action==="down"&&index<documentReportPages.length-1)[documentReportPages[index+1],documentReportPages[index]]=[documentReportPages[index],documentReportPages[index+1]];documentReportReady=false;renderDocumentReportPages();};
 byId("documentReportContinue").onclick=async()=>{if(!documentReportPages.length)return showToast("Bitte zuerst mindestens eine Seite fotografieren oder auswählen.","error");const button=byId("documentReportContinue");button.disabled=true;button.textContent="PDF wird erstellt …";try{await finalizeDocumentReportFiles();documentReportReady=true;panel.hidden=true;showToast(`${documentReportKind()} wurde als zugeschnittenes PDF gespeichert.`);if(sessionType==="Einsatz"){byId("operationReportForm")?.scrollIntoView({behavior:"smooth",block:"start"});}else openProbeTopicDialog();}catch(error){console.error(error);showToast("Das zugeschnittene PDF konnte nicht erzeugt werden.","error");}finally{button.disabled=false;button.textContent="Zugeschnittenes PDF übernehmen";}};
 return panel;
}
function showDocumentReportPanel(){
 const panel=ensureDocumentReportPanel();
 if(sessionType!=="Ausschuss Sitzung"&&!hasActiveAtue()){
   panel.hidden=true;
   return showToast("Foto der Atemschutzüberwachung ist erst möglich, wenn eine ATÜ-Person besetzt ist.","error");
 }
 panel.hidden=false;panel.style.display="block";panel.removeAttribute("aria-hidden");byId("documentReportTitle").textContent=documentReportKind();byId("documentReportSubtitle").textContent=documentReportSubtitle();renderDocumentReportPages();requestAnimationFrame(()=>panel.scrollIntoView({behavior:"smooth",block:"start"}));
}
function renderDocumentReportPages(){const box=byId("documentReportPages"),status=byId("documentReportStatus");if(!box||!status)return;status.textContent=documentReportPages.length?`${documentReportPages.length} Seite${documentReportPages.length===1?"":"n"} zugeschnitten. Reihenfolge bitte prüfen.`:"Noch keine Seite aufgenommen.";box.innerHTML=documentReportPages.map((page,index)=>`<article class="document-report-page"><img src="${page.url}" alt="Zugeschnittene Seite ${index+1}"><div><strong>Seite ${index+1}</strong><small>${page.width} × ${page.height} Pixel</small><span class="document-crop-badge">${page.manual?`manuell bearbeitet${page.rotation?` · ${page.rotation}°`:""}${page.straighten?` · ${page.straighten>0?"+":""}${page.straighten}° fein`:""}`:"automatisch zugeschnitten"}</span></div><div class="document-report-page-actions"><button type="button" data-page-action="up" data-page-id="${page.id}" ${index===0?"disabled":""}>Nach oben</button><button type="button" data-page-action="down" data-page-id="${page.id}" ${index===documentReportPages.length-1?"disabled":""}>Nach unten</button><button type="button" class="outline-button" data-page-action="crop" data-page-id="${page.id}">Manuell zuschneiden</button><button type="button" class="danger-button" data-page-action="delete" data-page-id="${page.id}">Löschen</button></div></article>`).join("");}
function ensureManualDocumentCropDialog(){
 let dialog=byId("manualDocumentCropDialog");if(dialog)return dialog;
 dialog=document.createElement("dialog");dialog.id="manualDocumentCropDialog";dialog.className="manual-document-crop-dialog";
 dialog.innerHTML=`<form method="dialog"><div class="manual-crop-head"><div><strong>Bild drehen und zuschneiden</strong><small>Mit zwei Fingern drehen oder die Regler verwenden. Der grüne Rahmen zeigt den PDF-Bereich.</small></div><button type="button" class="manual-crop-close" aria-label="Zuschneiden abbrechen">×</button></div><div class="manual-crop-preview"><canvas id="manualCropCanvas"></canvas><span class="two-finger-rotate-hint">↻ Mit zwei Fingern drehen</span></div><div class="manual-rotate-controls"><button type="button" class="outline-button" data-rotate-left>↶ 90° links</button><output data-rotation-output>0°</output><button type="button" class="outline-button" data-rotate-right>90° rechts ↷</button></div><div class="manual-straighten-control"><label><span>Fein ausrichten</span><output data-straighten-output>0°</output><input type="range" min="-45" max="45" value="0" step="0.5" data-straighten-angle></label><button type="button" class="outline-button" data-straighten-reset>Gerade stellen zurücksetzen</button></div><div class="manual-crop-controls"><label>Links entfernen <output data-crop-output="left">0 %</output><input type="range" min="0" max="40" value="0" step="1" data-crop-edge="left"></label><label>Rechts entfernen <output data-crop-output="right">0 %</output><input type="range" min="0" max="40" value="0" step="1" data-crop-edge="right"></label><label>Oben entfernen <output data-crop-output="top">0 %</output><input type="range" min="0" max="40" value="0" step="1" data-crop-edge="top"></label><label>Unten entfernen <output data-crop-output="bottom">0 %</output><input type="range" min="0" max="40" value="0" step="1" data-crop-edge="bottom"></label></div><div class="manual-crop-actions"><button type="button" class="outline-button" data-crop-auto>Automatischen Zuschnitt wiederherstellen</button><button type="button" class="outline-button" data-crop-cancel>Abbrechen</button><button type="button" class="primary-button" data-crop-apply>Zuschnitt übernehmen</button></div></form>`;
 document.body.appendChild(dialog);const preview=dialog.querySelector(".manual-crop-preview");preview.addEventListener("pointerdown",startManualCropGesture);preview.addEventListener("pointermove",moveManualCropGesture);preview.addEventListener("pointerup",endManualCropGesture);preview.addEventListener("pointercancel",endManualCropGesture);return dialog;
}
let manualCropState=null;
let manualCropGesture=null;
async function openManualDocumentCrop(index){
 const page=documentReportPages[index];if(!page)return;const dialog=ensureManualDocumentCropDialog(),bitmap=await createImageBitmap(page.file);manualCropState={index,page,bitmap,rotation:0,straighten:0,values:{left:0,right:0,top:0,bottom:0}};
 dialog.querySelectorAll("[data-crop-edge]").forEach(input=>{input.value="0";input.oninput=()=>{manualCropState.values[input.dataset.cropEdge]=Number(input.value);renderManualDocumentCrop();};});
 dialog.querySelector("[data-rotate-left]").onclick=()=>rotateManualDocumentCrop(-90);dialog.querySelector("[data-rotate-right]").onclick=()=>rotateManualDocumentCrop(90);const straighten=dialog.querySelector("[data-straighten-angle]");straighten.value="0";straighten.oninput=()=>{manualCropState.straighten=Number(straighten.value);renderManualDocumentCrop();};dialog.querySelector("[data-straighten-reset]").onclick=()=>{straighten.value="0";manualCropState.straighten=0;renderManualDocumentCrop();};dialog.querySelector("[data-crop-cancel]").onclick=()=>closeManualDocumentCrop(false);dialog.querySelector(".manual-crop-close").onclick=()=>closeManualDocumentCrop(false);
 dialog.querySelector("[data-crop-auto]").onclick=async()=>{closeManualDocumentCrop(false);const auto=await cropDocumentImage(page.file);replaceDocumentReportCrop(index,auto);};
 dialog.querySelector("[data-crop-apply]").onclick=applyManualDocumentCrop;dialog.oncancel=event=>{event.preventDefault();closeManualDocumentCrop(false);};renderManualDocumentCrop();dialog.showModal();
}
function normalizeGestureAngle(value){while(value>180)value-=360;while(value<-180)value+=360;return value;}
function gestureAngle(points){return Math.atan2(points[1].y-points[0].y,points[1].x-points[0].x)*180/Math.PI;}
function startManualCropGesture(event){if(!manualCropState)return;event.currentTarget.setPointerCapture?.(event.pointerId);if(!manualCropGesture)manualCropGesture={points:new Map(),baseAngle:0,baseStraighten:manualCropState.straighten};manualCropGesture.points.set(event.pointerId,{x:event.clientX,y:event.clientY});if(manualCropGesture.points.size===2){manualCropGesture.baseAngle=gestureAngle([...manualCropGesture.points.values()]);manualCropGesture.baseStraighten=manualCropState.straighten;event.preventDefault();}}
function moveManualCropGesture(event){if(!manualCropState||!manualCropGesture?.points.has(event.pointerId))return;manualCropGesture.points.set(event.pointerId,{x:event.clientX,y:event.clientY});if(manualCropGesture.points.size!==2)return;const current=gestureAngle([...manualCropGesture.points.values()]),delta=normalizeGestureAngle(current-manualCropGesture.baseAngle),next=Math.max(-45,Math.min(45,Math.round((manualCropGesture.baseStraighten+delta)*2)/2));manualCropState.straighten=next;const slider=byId("manualDocumentCropDialog")?.querySelector("[data-straighten-angle]");if(slider)slider.value=String(Math.max(-45,Math.min(45,next)));renderManualDocumentCrop();event.preventDefault();}
function endManualCropGesture(event){if(!manualCropGesture)return;manualCropGesture.points.delete(event.pointerId);if(manualCropGesture.points.size<2){manualCropGesture.baseStraighten=manualCropState?.straighten||0;if(!manualCropGesture.points.size)manualCropGesture=null;}}
function rotateManualDocumentCrop(delta){if(!manualCropState)return;manualCropState.rotation=(manualCropState.rotation+delta+360)%360;renderManualDocumentCrop();}
function drawRotatedBitmap(bitmap,angle,maxW=Infinity,maxH=Infinity){const radians=angle*Math.PI/180,cos=Math.abs(Math.cos(radians)),sin=Math.abs(Math.sin(radians)),rawW=Math.ceil(bitmap.width*cos+bitmap.height*sin),rawH=Math.ceil(bitmap.width*sin+bitmap.height*cos),scale=Math.min(1,maxW/rawW,maxH/rawH),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(rawW*scale));canvas.height=Math.max(1,Math.round(rawH*scale));const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(radians);ctx.drawImage(bitmap,-bitmap.width*scale/2,-bitmap.height*scale/2,bitmap.width*scale,bitmap.height*scale);return canvas;}
function renderManualDocumentCrop(){
 if(!manualCropState)return;const {bitmap,rotation,straighten,values}=manualCropState,dialog=byId("manualDocumentCropDialog"),canvas=byId("manualCropCanvas"),rotated=drawRotatedBitmap(bitmap,rotation+straighten,760,560);canvas.width=rotated.width;canvas.height=rotated.height;const ctx=canvas.getContext("2d");ctx.drawImage(rotated,0,0);const left=canvas.width*values.left/100,right=canvas.width*(1-values.right/100),top=canvas.height*values.top/100,bottom=canvas.height*(1-values.bottom/100);ctx.fillStyle="rgba(0,0,0,.55)";ctx.fillRect(0,0,canvas.width,top);ctx.fillRect(0,bottom,canvas.width,canvas.height-bottom);ctx.fillRect(0,top,left,bottom-top);ctx.fillRect(right,top,canvas.width-right,bottom-top);ctx.strokeStyle="#35d06f";ctx.lineWidth=3;ctx.strokeRect(left,top,Math.max(1,right-left),Math.max(1,bottom-top));dialog.querySelector("[data-rotation-output]").textContent=`${rotation}°`;dialog.querySelector("[data-straighten-output]").textContent=`${straighten>0?"+":""}${straighten}°`;dialog.querySelectorAll("[data-crop-output]").forEach(output=>output.textContent=`${values[output.dataset.cropOutput]} %`);
}
async function applyManualDocumentCrop(){
 if(!manualCropState)return;const {index,bitmap,rotation,straighten,values}=manualCropState;if(values.left+values.right>=85||values.top+values.bottom>=85)return showToast("Der verbleibende Bildbereich ist zu klein.","error");const rotated=drawRotatedBitmap(bitmap,rotation+straighten),sx=Math.round(rotated.width*values.left/100),sy=Math.round(rotated.height*values.top/100),sw=Math.max(1,Math.round(rotated.width*(100-values.left-values.right)/100)),sh=Math.max(1,Math.round(rotated.height*(100-values.top-values.bottom)/100)),maxSide=2400,scale=Math.min(1,maxSide/Math.max(sw,sh)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(sw*scale));canvas.height=Math.max(1,Math.round(sh*scale));canvas.getContext("2d").drawImage(rotated,sx,sy,sw,sh,0,0,canvas.width,canvas.height);const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Bild konnte nicht bearbeitet werden")),"image/jpeg",.9));replaceDocumentReportCrop(index,{blob,width:canvas.width,height:canvas.height,crop:{x:sx,y:sy,width:sw,height:sh},rotation,straighten,manual:true});closeManualDocumentCrop(true);
}
function replaceDocumentReportCrop(index,cropped){const page=documentReportPages[index];if(!page)return;URL.revokeObjectURL(page.url);page.blob=cropped.blob;page.url=URL.createObjectURL(cropped.blob);page.width=cropped.width;page.height=cropped.height;page.crop=cropped.crop;page.rotation=cropped.rotation||0;page.straighten=cropped.straighten||0;page.manual=Boolean(cropped.manual);documentReportReady=false;renderDocumentReportPages();}
function closeManualDocumentCrop(applied){const dialog=byId("manualDocumentCropDialog");manualCropState?.bitmap?.close?.();manualCropState=null;manualCropGesture=null;if(dialog?.open)dialog.close();if(applied)showToast("Manueller Zuschnitt wurde übernommen.");}
async function cropDocumentImage(file){
 const bitmap=await createImageBitmap(file),maxSide=2400,scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),source=document.createElement("canvas");source.width=Math.max(1,Math.round(bitmap.width*scale));source.height=Math.max(1,Math.round(bitmap.height*scale));const context=source.getContext("2d",{willReadFrequently:true});context.drawImage(bitmap,0,0,source.width,source.height);bitmap.close?.();
 const sampleScale=Math.min(1,900/Math.max(source.width,source.height)),probe=document.createElement("canvas");probe.width=Math.max(1,Math.round(source.width*sampleScale));probe.height=Math.max(1,Math.round(source.height*sampleScale));const pctx=probe.getContext("2d",{willReadFrequently:true});pctx.drawImage(source,0,0,probe.width,probe.height);const data=pctx.getImageData(0,0,probe.width,probe.height).data;
 const darkCol=new Uint16Array(probe.width),darkRow=new Uint16Array(probe.height);for(let y=0;y<probe.height;y++){for(let x=0;x<probe.width;x++){const i=(y*probe.width+x)*4,luma=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2],spread=Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2]);if(luma<232||spread>24){darkCol[x]++;darkRow[y]++;}}}
 const colLimit=Math.max(2,Math.round(probe.height*.012)),rowLimit=Math.max(2,Math.round(probe.width*.012));let left=0,right=probe.width-1,top=0,bottom=probe.height-1;while(left<right&&darkCol[left]<colLimit)left++;while(right>left&&darkCol[right]<colLimit)right--;while(top<bottom&&darkRow[top]<rowLimit)top++;while(bottom>top&&darkRow[bottom]<rowLimit)bottom--;
 const margin=Math.max(8,Math.round(Math.min(probe.width,probe.height)*.018));left=Math.max(0,left-margin);right=Math.min(probe.width-1,right+margin);top=Math.max(0,top-margin);bottom=Math.min(probe.height-1,bottom+margin);if((right-left)<probe.width*.45||(bottom-top)<probe.height*.45){left=0;right=probe.width-1;top=0;bottom=probe.height-1;}
 const ratio=1/sampleScale,sx=Math.round(left*ratio),sy=Math.round(top*ratio),sw=Math.min(source.width-sx,Math.round((right-left+1)*ratio)),sh=Math.min(source.height-sy,Math.round((bottom-top+1)*ratio)),out=document.createElement("canvas");out.width=sw;out.height=sh;out.getContext("2d").drawImage(source,sx,sy,sw,sh,0,0,sw,sh);const blob=await new Promise((resolve,reject)=>out.toBlob(value=>value?resolve(value):reject(new Error("Bild konnte nicht zugeschnitten werden")),"image/jpeg",.9));return {blob,width:sw,height:sh,crop:{x:sx,y:sy,width:sw,height:sh}};
}
function asciiBytes(value){return new TextEncoder().encode(value);}
function concatBytes(parts){const size=parts.reduce((sum,part)=>sum+part.length,0),out=new Uint8Array(size);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}
async function buildDocumentReportPdf(){const objects=[null],add=value=>(objects.push(value),objects.length-1),pagesId=add(null),pageIds=[];for(const page of documentReportPages){const bytes=new Uint8Array(await page.blob.arrayBuffer()),imageId=add(concatBytes([asciiBytes(`<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`),bytes,asciiBytes("\nendstream")])),a4w=595,a4h=842,margin=18,availableW=a4w-margin*2,availableH=a4h-margin*2,ratio=Math.min(availableW/page.width,availableH/page.height),w=page.width*ratio,h=page.height*ratio,x=(a4w-w)/2,y=(a4h-h)/2,stream=`q ${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Img Do Q`,streamBytes=asciiBytes(stream),contentId=add(concatBytes([asciiBytes(`<< /Length ${streamBytes.length} >>\nstream\n`),streamBytes,asciiBytes("\nendstream")]));pageIds.push(add(asciiBytes(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${a4w} ${a4h}] /Resources << /XObject << /Img ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`)));}objects[pagesId]=asciiBytes(`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] >>`);const catalog=add(asciiBytes(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`)),parts=[asciiBytes("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n")],offsets=[0];let length=parts[0].length;for(let i=1;i<objects.length;i++){offsets[i]=length;const part=concatBytes([asciiBytes(`${i} 0 obj\n`),objects[i],asciiBytes("\nendobj\n")]);parts.push(part);length+=part.length;}const xref=length;let tail=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)tail+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";tail+=`trailer\n<< /Size ${objects.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(asciiBytes(tail));return new Blob(parts,{type:"application/pdf"});}
async function openDocumentReportDb(){return await new Promise((resolve,reject)=>{const request=indexedDB.open("ffw-document-reports",1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("reports"))db.createObjectStore("reports",{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function saveDocumentReportRecord(record){const db=await openDocumentReportDb();await new Promise((resolve,reject)=>{const tx=db.transaction("reports","readwrite");tx.objectStore("reports").put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
async function finalizeDocumentReportFiles(){const id=`${today()}_${sessionType.replace(/\s+/g,"-")}_${Date.now()}`,safe=sessionType.replace(/\s+/g,"-"),suffix=sessionType==="Ausschuss Sitzung"?"Sitzungsbericht":"ATUE-Bericht",pdf=await buildDocumentReportPdf(),pdfName=`FFW-Wasser_${today()}_${safe}_${suffix}.pdf`;pendingDocumentReport={id,archiveEntryId:"",operationId:sessionType==="Einsatz"?(currentOperationId||""):"",date:today(),sessionType,kind:documentReportKind(),atueMember:sessionType==="Einsatz"?(byId("opAtuePerson")?.value||""):(currentAtueMember?nameForTile(currentAtueMember):""),pageCount:documentReportPages.length,pdf,pdfName,createdAt:new Date().toISOString(),processing:"cropped-image-pdf"};}
async function commitPendingDocumentReport(archiveEntryId){if(!pendingDocumentReport)return null;const record={...pendingDocumentReport,archiveEntryId:String(archiveEntryId||"")};await saveDocumentReportRecord(record);pendingDocumentReport=null;return record.id;}
async function allDocumentReports(){const db=await openDocumentReportDb();const items=await new Promise((resolve,reject)=>{const r=db.transaction("reports","readonly").objectStore("reports").getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);});db.close();return items;}
async function exportDocumentReports(){const items=[];for(const record of await allDocumentReports()){items.push({...record,pdf:undefined,pdfDataUrl:record.pdf?await blobToDataUrl(record.pdf):""});}return items;}
async function restoreDocumentReports(items){let count=0;for(const item of Array.isArray(items)?items:[]){if(!item?.id||!item?.pdfDataUrl)continue;await saveDocumentReportRecord({...item,pdf:dataUrlToBlob(item.pdfDataUrl),pdfDataUrl:undefined});count++;}return count;}
async function deleteDocumentReportsForArchive(archiveEntryId){const db=await openDocumentReportDb();const all=await new Promise((resolve,reject)=>{const r=db.transaction("reports","readonly").objectStore("reports").getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);});await new Promise((resolve,reject)=>{const tx=db.transaction("reports","readwrite"),store=tx.objectStore("reports");all.filter(item=>item.archiveEntryId===archiveEntryId).forEach(item=>store.delete(item.id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
async function prepareDocumentReportBeforeClose(){if(!documentReportRequired())return true;if(documentReportReady)return true;showDocumentReportPanel();showToast(`${documentReportKind()} bitte fotografieren oder auswählen.`,"error");return false;}
